### ISSUE TITLE
Additional file ending "*.dio"

### ISSUE THREAD

**Issue by yngwi** [hediet/vscode-drawio#1]
Hi,
it would be great if you could add "*.dio" as an additional file ending (if possible) for draw.io files as this ending is used in the Jupyterlab extension [jupyterlab-drawio](https://github.com/QuantStack/jupyterlab-drawio/).
Thanks!
Daniel

**Comment by hediet** [comment]
Hi Daniel ;)
Thanks for your input!
Do you have an example for such a dio file? Is it just an alias for drawio and thus also an xml document?

**Comment by yngwi** [comment]
Hi.
As far as I can tell it's the same file the ending is just an alias. I don't know why they chose the different ending, as far as I can tell .drawio seems to be the official ending used by draw.io. Maybe they wanted to stick to 3 letters as with most other endings. Now that I think about it I should post a feature request at their repo.

**Comment by hediet** [comment]
0.1.3. now supports the *.dio file extension.

**Comment by yngwi** [comment]
wow thank you
