### ISSUE TITLE
Code Link Feature doesn't work

### ISSUE THREAD

**Issue by buyixiaojiang** [hediet/vscode-drawio#105]
> Code Link Feature. In the status bar, you can enable or disable the code link feature. 

I didn't find the switch to enable it

**Comment by hediet** [comment]
It's released with the latest insiders build! It's a separate extension (Draw.io Integration Insiders Build). If you like, please install it and report whether it works!
If it works for enough people, I will release the insiders build as the main extension. Releasing to an insiders extension first helps me to assure quality for the main extension.

What do you think of this approach? Do you have ideas how I can encourage users of the insiders build extension to report whether the build works or not?

As a windows user I can only test so much. Also, testing is something where other people can help me very easily and very efficiently.

**Comment by buyixiaojiang** [comment]
>  If you like, please install it and report whether it works!
Could you tell me how to install it? I have already install the Draw.io Integration extension

**Comment by hediet** [comment]
You can find it here: https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio-insiders-build

You should uninstall the main Draw.io Integration extension though.

**Comment by hediet** [comment]
I just released the feature.

**Comment by buyixiaojiang** [comment]
I can see the new version 0.7.2. But I uninstalled it and install it and the version is also 0.6.6. I tried a few times. If it works right   later, I will comment in the below.

`What do you think of this approach? Do you have ideas how I can encourage users of the insiders build extension to report whether the build works or not?`

It's good way to enable it in the settings and the default value is the false. Maybe some good demos can encourage the users. If I use it very convenient, I will provide some demos.

**Comment by hediet** [comment]
Do you use the latest vs code? Which version do you use?

**Comment by buyixiaojiang** [comment]
I updated the vs code and it works. 
Another question is how can I modify the label text value? Because when I double click the label which starts with # , it focus on the code section

**Comment by hediet** [comment]
You can either press F2, I think, or temporarily disable the code link feature in the statusbar by clicking on it.

**Comment by buyixiaojiang** [comment]
I tried and it works.

 I think the better way is  double click and  press Command/Ctrl ,  then jump into the code section

**Comment by hediet** [comment]
I can make the ctrl modifier required if code link is disabled.
