### ISSUE TITLE
Does not work with Stable VSCode

### ISSUE THREAD

**Issue by Ciantic** [hediet/vscode-drawio#106]
Opening this as requested: https://github.com/hediet/vscode-drawio/issues/101#issuecomment-650832714

It doesn't work with stable VSCode for me.  I tried to create empty file `architecture.dio` but I get just this:

![image](https://user-images.githubusercontent.com/64731/85957260-9ab3e280-b994-11ea-9960-6df8fb4f835b.png)

![image](https://user-images.githubusercontent.com/64731/85957271-a99a9500-b994-11ea-9086-c65dadf0af0e.png)

![image](https://user-images.githubusercontent.com/64731/85957291-d5b61600-b994-11ea-82b7-f8aa44017fab.png)

Things I've tried:

Restarting VSCode, reinstalling the drawio extension, installing insider version of the extension, re-opening the tab or the file in the drawio. Renaming architecture.dio to architecture.dio.svg. It just doesn't work for me.

**Comment by Ciantic** [comment]
Drawio Integration Log:

![image](https://user-images.githubusercontent.com/64731/86011527-7522e980-ba25-11ea-9ed3-b58811249051.png)

**Comment by hediet** [comment]
Thanks for you bug report and for trying out all the things! Can you open the webview dev tools and send a screenshot of the logs there?

**Comment by Ciantic** [comment]
Sure.

![image](https://user-images.githubusercontent.com/64731/86018980-b4096d00-ba2e-11ea-91bf-a9059e8874e4.png)

I forgot this gem, I'll try to investigate why the file access is denied. This might be something with my file system.

**Comment by Ciantic** [comment]
Yes! Something got screwed in my file system, I did some icacls tricks and it now works. Windows is awesome.

Apologies, I will close this.

**Comment by hediet** [comment]
Glad to hear that it works! Yeah, Windows is awesome :P
