### ISSUE TITLE
Unable to change UI-scale (hard to read on high resolution laptop)

### ISSUE THREAD

**Issue by nc-nsre** [hediet/vscode-drawio#11]
The text is really small and seems hard to read. I was looking for a setting to set the UI-scale, but was unable to find it.

**Comment by hediet** [comment]
Can you provide a screenshot or a photo? If you use the zoom command of VS Code, webviews are zoomed too.
Also, I'm working on a 4k monitor with 150% scaling by Windows and have no issues.

**Comment by nc-nsre** [comment]
Hi @hediet 

That did the trick 😉
