### ISSUE TITLE
Cannot modify file side by side

### ISSUE THREAD

**Issue by PierreMarchand20** [hediet/vscode-drawio#111]
When I modify the svg file, it does not update the UI:
![Kapture 2020-07-04 at 20 48 39](https://user-images.githubusercontent.com/15056323/86519103-d7ba2200-be37-11ea-891a-607806728593.gif)

**Comment by hediet** [comment]
This is by design. Drawio does not process the svg, but only the drawio metadata (see the content attribute) inside the svg.
Use the drawio file extension to be able to edit the xml document.
