### ISSUE TITLE
Shortcut conflict (Ctrl+B)

### ISSUE THREAD

**Issue by sthulb** [hediet/vscode-drawio#112]
When editing the text inside a shape, pressing cmd+b toggles bold, but also toggles the file browser panel.

**Comment by hediet** [comment]
Is it doing both at the same time? Do you have an idea how to solve this conflict?

**Comment by sthulb** [comment]
Unfortunately, yes.

As for a solve, unsure.

**Comment by liyang85** [comment]
I faced a similar situation: when I open Draw.io UI in VS Code, I want to call the `Command Palette` by the keyboard shortcut `Cmd + Shift + P`, but it always toggles the right sidebar of Draw.io! Finally, I have to click the gear icon of VS Code to find the menu item.

**Comment by hediet** [comment]
Have you enabled the online mode of the extension?

**Comment by liyang85** [comment]
Hi @hediet, I didn't change any default setting, so I think I have been using the offline version. Below are the details:

![image](https://user-images.githubusercontent.com/20695423/87899204-0c0e1f00-ca83-11ea-8adc-899b1be99927.png)

And there is only one related setting in my `settings.json`, which was added by this extension itself:

```json
"hediet.vscode-drawio.local-storage": "eyIuZHJhd2lvLWNvbmZpZyI6IntcImxhbmd1YWdlXCI6XCJcIixcImN1c3RvbUZvbnRzXCI6W10sXCJsaWJyYXJpZXNcIjpcImdlbmVyYWw7dW1sO2VyO2JwbW47Zmxvd2NoYXJ0O2Jhc2ljO2Fycm93czJcIixcImN1c3RvbUxpYnJhcmllc1wiOltcIkwuc2NyYXRjaHBhZFwiXSxcInBsdWdpbnNcIjpbXSxcInJlY2VudENvbG9yc1wiOltdLFwiZm9ybWF0V2lkdGhcIjoyNDAsXCJjcmVhdGVUYXJnZXRcIjpmYWxzZSxcInBhZ2VGb3JtYXRcIjp7XCJ4XCI6MCxcInlcIjowLFwid2lkdGhcIjo4MjcsXCJoZWlnaHRcIjoxMTY5fSxcInNlYXJjaFwiOnRydWUsXCJzaG93U3RhcnRTY3JlZW5cIjp0cnVlLFwiZ3JpZENvbG9yXCI6XCIjZDBkMGQwXCIsXCJkYXJrR3JpZENvbG9yXCI6XCIjNmU2ZTZlXCIsXCJhdXRvc2F2ZVwiOnRydWUsXCJyZXNpemVJbWFnZXNcIjpudWxsLFwib3BlbkNvdW50ZXJcIjowLFwidmVyc2lvblwiOjE4LFwidW5pdFwiOjEsXCJpc1J1bGVyT25cIjpmYWxzZSxcInVpXCI6XCJcIn0ifQ==",
```

**Comment by hediet** [comment]
Your issue does not happen for me on windows 10.
Can you share more details?

**Comment by liyang85** [comment]
Sure.

System info copied from `About Visual Studio Code`:

```txt
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Draw.io Integration version: `v0.7.2`

Anything else do you need?

**Comment by hediet** [comment]
This might be really hard to debug. Conceptually, I'm not really in control of handling/forwarding these events - I usually observe how vscode and drawio behave and try to fix what does not work (this is ugly, but there is no way around that).

Since this seem to work on windows and I don't and never will have a Mac (*), I cannot debug it and understand what is causing the problem.

(*) for the reason alone that I don't want to spend money on something I don't make money from. I hate apple for not offering a free for developer Mac VM.

**Comment by liyang85** [comment]
Got it and understood. Still thank you for the product. 😄

**Comment by cathaypacific8747** [comment]
This issue seems to occur on Windows too, vscode-drawio version is `1.6.502 (Insider Build)`:
Visual Studio Code: 
```
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows NT x64 10.0.22000
```
