### ISSUE TITLE
Keep export zoom settings for .drawio.png

### ISSUE THREAD

**Issue by AdamCoulterOz** [hediet/vscode-drawio#114]
I often change the export settings for png to 200% or 300% to increase the image quality, especially if there is small text. When I save with this extension it changes it back 100%. Is there a way to change a setting to automatically export at a given zoom %?

This is great btw... I've been wanting someone to integrate drawio with source control / IDE for like 2 years... great work!

**Comment by hediet** [comment]
How do you change the export settings for png?

**Comment by AdamCoulterOz** [comment]
> How do you change the export settings for png?

File > Export as > PNG

<img width="1024" alt="Screen Shot 2020-07-22 at 4 00 41 pm" src="https://user-images.githubusercontent.com/6822248/88140177-947ff180-cc34-11ea-9153-f35e8310b1b5.png">

**Comment by DennisSmolek** [comment]
Reading the latest docs from draw.io says [zoom isn't supported from the "Export" message.](https://desk.draw.io/support/solutions/articles/16000051938-comparing-embed-export-formats)


But in some of the other examples there are more parameters that can be passed than what they show in the schema...

I think they just haven't gotten to documenting it or setting it up yet...

**Comment by hediet** [comment]
If you find out which parameter, I could implement this quickly!

**Comment by AdamCoulterOz** [comment]
> @DennisSmolek: Reading the latest docs from draw.io says [zoom isn't supported from the "Export" message.](https://desk.draw.io/support/solutions/articles/16000051938-comparing-embed-export-formats)
> 
> But in some of the other examples there are more parameters that can be passed than what they show in the schema...
> 
> I think they just haven't gotten to documenting it or setting it up yet...

It was also last Modified on: Wed, 14 Jun, 2017 at 8:31 AM

:-)

**Comment by AdamCoulterOz** [comment]
> If you find out which parameter, I could implement this quickly!

@hediet looks like the `s` argument here represents an integer percentage `s = scaling` factor.

https://github.com/jgraph/drawio/blob/f1ee613245cf8d3d9303a464e3b6d999a0913c98/src/main/webapp/js/mxgraph/Dialogs.js#L1189

but the drawio document format doesn't have a way to store this value, we would need to store it somewhere in the file, and read it during export

**Comment by DennisSmolek** [comment]
> @hediet looks like the `s` argument here represents an integer percentage `s = scaling` factor.
> 
> 
> 
> https://github.com/jgraph/drawio/blob/f1ee613245cf8d3d9303a464e3b6d999a0913c98/src/main/webapp/js/mxgraph/Dialogs.js#L1189
> 
> 
> 
> 

Interesting find...

I think the problem though is the export logic isn't handled by the export dialogue directly but through draw.io's embedded Message Channel API which doesn't list scale/zoom factor as a parameter.

You could fork the draw.io repo and add/Re-write the logic to include it or maybe do some of the overriding/hoisting done to suppress other regular features (localhost, languages, etc)

@AdamCoulterOz I  didn't take a look yet but maybe you can find the export logic in the main library like you did for the dialog?

**Comment by hediet** [comment]
We could also monkey patch some drawio function or open an issue in their repository or open a PR. Drawio is open source ;) 
Yeah, I'm unsure too how to save the zoom factor. Best would be in the diagram itself.

**Comment by nopeslide** [comment]
> Yeah, I'm unsure too how to save the zoom factor.

maybe introduce a vscode option for the time being?
export settings are at least project dependent

**Comment by hediet** [comment]
Yeah, but this is blocked by jgraph/drawio#1155 anyways.

**Comment by nopeslide** [comment]
> Yeah, but this is blocked by [jgraph/drawio#1155](https://github.com/jgraph/drawio/issues/1155) anyways.

Do you have any insight of the drawio development?
seems rather slow for a commercially available product

**Comment by hediet** [comment]
> Do you have any insight into the drawio development?

No, sadly not.

> seems rather slow for a commercially available product

it is commercially only in connection with atlassian I think. The online editor is just open source and free.

**Comment by hediet** [comment]
This is now implemented in 1.3.0-alpha.1. Also, so #194.

**Comment by zmbc** [comment]
In case anyone comes here and can't find how to do this within VSCode, like me:

<img width="465" height="296" alt="Image" src="https://github.com/user-attachments/assets/d65f5916-096b-4dad-be3e-9d320ba560c4" />
