### ISSUE TITLE
Extra copy created on copy paste

### ISSUE THREAD

**Issue by Mkassabov** [hediet/vscode-drawio#115]
When using copy paste on elements via keyboard shortcuts (e.g. ctrl + c, ctrl + v) 2 copies are created, for a total of 3 versions of the original element. This doesn't occur when copy pasting via the context menu

**Comment by hediet** [comment]
I cannot reproduce this on windows 10 and the latest vscode. Can you share more info?

**Comment by Mkassabov** [comment]
VSCode about:
> Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

win 10 info:
>OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

any other specific information you need?

**Comment by Mkassabov** [comment]
Managed to fit it by removing and reinstalling the extension. weird.

**Comment by hediet** [comment]
That is weird. Maybe you had an old version of the extension.

**Comment by jbeyer16** [comment]
Possibly related to a bigger VSCode problem with copy paste and webviews.

https://github.com/microsoft/vscode/issues/101946
