### ISSUE TITLE
Paste is happening twice

### ISSUE THREAD

**Issue by voor** [hediet/vscode-drawio#116]
Whenever I paste an object with Ctrl+V it happens twice.

See video at https://youtu.be/qCTFT8GIZzc

Draw.io Integration v0.7.2

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T00:13:57.513Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.8-200.fc32.x86_64
```

**Comment by voor** [comment]
Only happens once if I right click and choose "Paste Here"

**Comment by hediet** [comment]
See #115. Does that fix it for you?

**Comment by voor** [comment]
Thank you for the super fast response time.  Unfortunately uninstalling and reinstalling did not resolve it, I believe it is related to an issue with 1.47.1 of VSCode.

**Comment by hediet** [comment]
Does this still happen in VS Code Insiders?

**Comment by DennisSmolek** [comment]
This was an issue with VS Code itself: https://github.com/microsoft/vscode/issues/101946
Looks like it's starting to go out but there are still a ton of new/active comments.

**Comment by HansUXdev** [comment]
Yeah I saw this too.

**Comment by hediet** [comment]
Does this still happen? E.g. with vscode insiders?

**Comment by voor** [comment]
Sorry took a while to circle back, this does not happen with VS Code Insiders, closing issue as unrelated to this extension.
