### ISSUE TITLE
Ctrl+B event not caught

### ISSUE THREAD

**Issue by jnnksdev** [hediet/vscode-drawio#123]
Ctrl+B can bold/unbold a text. When selecting an item the behavior is as expected.
When [editing the text](https://user-images.githubusercontent.com/33757567/91635007-1a8e1580-e9f5-11ea-8b4e-62ad3c4f006b.png) of an item and pressing Ctrl+B the VSCode file tree toggles as well.

**Comment by hediet** [comment]
Thanks for reporting this issue! I think it is the same problem as described in #112.
