### ISSUE TITLE
Minor UI issue

### ISSUE THREAD

**Issue by capedghost** [hediet/vscode-drawio#128]
I have turned off the Breadcrumbs:
![S20200926112522](https://user-images.githubusercontent.com/44280081/94329163-1e5c8a00-ffeb-11ea-9d05-e7e2e8b1047f.png)
Then there is a blank bar, at the position of the Breadcrumbs:
![S20200926112331](https://user-images.githubusercontent.com/44280081/94329182-4815b100-ffeb-11ea-9d3d-78b751f9977b.png)
It's a little ugly.

**Comment by capedghost** [comment]
Oh, I turn off the Breadcrumbs first and then install the extension, it's ok now:
![S20200926152414](https://user-images.githubusercontent.com/44280081/94335227-a4d59380-000c-11eb-8853-01a601abe9cd.png)

**Comment by capedghost** [comment]
And I found a new issue, some UI font:
![S20200926152951](https://user-images.githubusercontent.com/44280081/94335303-4fe64d00-000d-11eb-8459-0fa0ef265e27.png)
![S20200926152959](https://user-images.githubusercontent.com/44280081/94335307-570d5b00-000d-11eb-9f76-3b3285fc3fec.png)
It dimmed.

**Comment by hediet** [comment]
Thanks for your report!

> I have turned off the Breadcrumbs:
> ![S20200926112522](https://user-images.githubusercontent.com/44280081/94329163-1e5c8a00-ffeb-11ea-9d05-e7e2e8b1047f.png)
> Then there is a blank bar, at the position of the Breadcrumbs:
> ![S20200926112331](https://user-images.githubusercontent.com/44280081/94329182-4815b100-ffeb-11ea-9d3d-78b751f9977b.png)
> It's a little ugly.

Can you try this with the hex editor? It's an official vscode extension. I doubt I can do anything here. 

Could you also please open individual issues for the other issues you reported? 

Can

**Comment by capedghost** [comment]
> Thanks for your report!
> 
> > I have turned off the Breadcrumbs:
> > ![S20200926112522](https://user-images.githubusercontent.com/44280081/94329163-1e5c8a00-ffeb-11ea-9d05-e7e2e8b1047f.png)
> > Then there is a blank bar, at the position of the Breadcrumbs:
> > ![S20200926112331](https://user-images.githubusercontent.com/44280081/94329182-4815b100-ffeb-11ea-9d3d-78b751f9977b.png)
> > It's a little ugly.
> 
> Can you try this with the hex editor? It's an official vscode extension. I doubt I can do anything here.
> 
> Could you also please open individual issues for the other issues you reported?
---
I tried the Hex editor, it seems it's also have this problem:
![S20200926171556](https://user-images.githubusercontent.com/44280081/94337407-aeff8e00-001c-11eb-8e17-6571a409ece3.png)
![S20200926171441](https://user-images.githubusercontent.com/44280081/94337414-b9ba2300-001c-11eb-996e-f7c623925540.png)
---
And, okay, I will open an individual issue for the other issue, maybe two, because I found a new issue again.

**Comment by hediet** [comment]
> I tried the Hex editor, it seems it's also have this problem:

In this case, this is a vscode issue. There is nothing I can do about it. Feel free to open an issue in their repo!
