### ISSUE TITLE
UI font problem

### ISSUE THREAD

**Issue by capedghost** [hediet/vscode-drawio#129]
Some UI font:
![image](https://user-images.githubusercontent.com/44280081/94337692-21716d80-001f-11eb-8c4a-90c906d7315e.png)
![image](https://user-images.githubusercontent.com/44280081/94337698-29311200-001f-11eb-86c6-a380990bf02e.png)
It's dimmed.

**Comment by hediet** [comment]
Can you tell me which versions of vscode and the drawio extension you use? And which themes? Thanks!

**Comment by capedghost** [comment]
> Can you tell me which versions of vscode and the drawio extension you use? And which themes? Thanks!

Vscode：
![S20200926210246](https://user-images.githubusercontent.com/44280081/94341440-d6198800-003b-11eb-9342-7f34f607b076.png)
drawio extension：
![S20200926210329](https://user-images.githubusercontent.com/44280081/94341457-f8130a80-003b-11eb-9a49-90e1b3eb6736.png)
The themes:
![S20200926210612](https://user-images.githubusercontent.com/44280081/94341478-35779800-003c-11eb-9fc2-15191607fa05.png)

**Comment by hediet** [comment]
Fixed in insiders build.
