### ISSUE TITLE
The file name extension  problem

### ISSUE THREAD

**Issue by capedghost** [hediet/vscode-drawio#130]
Look

I create a new file (by double click the tabs bar), and then save it, rename it with the extension ".mmd", support by Mermaid Editor vscode plugin.
![S20200926172720](https://user-images.githubusercontent.com/44280081/94337878-60ec8980-0020-11eb-8ec4-3edbbabd8ff6.png)
Then I get test1.mmd
![S20200926172931](https://user-images.githubusercontent.com/44280081/94337893-7e215800-0020-11eb-8bf4-63f77fe728fd.png)

---
I create a new file again, save it, rename it with extension “.drawio”：
![S20200926172901](https://user-images.githubusercontent.com/44280081/94337985-4b2b9400-0021-11eb-83d9-b204af4b30ec.png)
Then  I get "test1.drawio.txt"
![S20200926172943](https://user-images.githubusercontent.com/44280081/94338019-9c3b8800-0021-11eb-82f1-0f3baa7037b9.png)
---
In the Save as dialog, the extension name for drawio is not listed in it:
![S20200926175927](https://user-images.githubusercontent.com/44280081/94338115-76fb4980-0022-11eb-9219-b7e7612f5050.png)
---
I create "test2.drawio" directly on desktop, and open it with vscode.
It's working, but:
![S20200926180455](https://user-images.githubusercontent.com/44280081/94338216-191b3180-0023-11eb-82ef-a3a681860994.png)
vscode still suggests me to get a extension to handle ".drawio" file.

**Comment by hediet** [comment]
Should be fixed now.

**Comment by capedghost** [comment]
> Should be fixed now.
Yes, It's fixed now, Thank you.

em...but, not completely.
I create a new file,
save it with name "test.dio", 
then:
![S20201006085305](https://user-images.githubusercontent.com/44280081/95146882-aee85680-07b1-11eb-87b4-59e195b94ebf.png)
The drawio editor still won't run automatically.

I need to close this tab, and reopen this file, then drawio editor will run automatically when this file opened.
I'm sorry, I don't know if I'm asking too much.

Is this problem due to VScode itself？

**Comment by hediet** [comment]
> Is this problem due to VScode itself？

Sadly, yes. I think my issue in vscode's repo got marked as unimportant and was closed. But feel free to open another one!
If you create the file in the explorer from the sidebar, it should work though.

**Comment by capedghost** [comment]
> Sadly, yes. I think my issue in vscode's repo got marked as unimportant and was closed. But feel free to open another one!
> If you create the file in the explorer from the sidebar, it should work though.

Okay, fine. 
Create file from sidebar will work, This approach is good enough.
Thank you.
