### ISSUE TITLE
Opening a .drawio file gets stuck and reopening doesn't fix it

### ISSUE THREAD

**Issue by dlight** [hediet/vscode-drawio#141]
Hello, previously this extension worked fine, but after some update months ago it gets stuck in this screen:

> Flowchart Maker and Online Diagram Software
diagrams.net (formerly draw.io) is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw.io can import .vsdx, Gliffy™ and Lucidchart™ files .

> Loading...
> If you see this message longer than a few seconds, it probably broke due to [this issue](https://github.com/microsoft/vscode/issues/89038). Just reopen this file. Future versions of VS Code might fix this bug.

However, the issue linked seems unrelated; reloading the file or even VSCode itself doesn't fix the issue.

Opening the file with the desktop drawio package (installed from [this aur package](https://aur.archlinux.org/packages/drawio-desktop-bin/)) loads the diagram fine (after briefly showing the "Flowchart Maker and Online Diagram Software" message).

I'm running Code - OSS 1.49.1 and Draw.io Integration v999.0.0-alpha (published 10 days ago).

I thought about attaching my diagram but even a blank diagram created by the drawio standalone app will not load in the VSCode extension.

**Comment by hediet** [comment]
Hi ;) 

I never published a version v999.0! It seems like you are using the unofficial open vsx marketplace (where, apparently, anyone can upload anything). You can find an issue here in this repository about it.
Unfortunately, someone uploaded the extension in that version which blocks any further updates with that name.
For now I believe in Microsofts vision. I don't think a secondary marketplace is good for the community - It just causes confusions like this.

If you setup a github action that automatically publishes this extension to open vsx, please open a PR! ;)

**Comment by KEINOS** [comment]
I get the same message as below. Though, I installed `hediet.vscode-drawio` via the official marketplace.

<kbd>![スクリーンショット 2020-10-07 10 17 54](https://user-images.githubusercontent.com/11840938/95290214-ad00bf00-08a7-11eb-8151-96a49b4ee9df.png)</kbd>

Re-opening the file nor re-opening the VSCode didn't take effect.

Opening the URL, `https://embed.diagrams.net/`, which is also set in the extension's setting, on Chrome works fine. 

Here's my env info. Is there any other info that I should provide to help?

- Draw.io Integration: v1.0.0 (2020-10-04 release)
- VSCode: v1.49.3
  - Electron: 9.2.1
  - Chrome: 83.0.4103.122
  - Node.js: 12.14.1
  - V8: 8.3.110.13-electron.0
  - OS: Darwin x64 19.6.0 (macOS Catalina 10.15.7)

**Comment by hediet** [comment]
@keinos does the hex editor work for you? It's a ms extension. Can you open both in parallel?

**Comment by KEINOS** [comment]
@hediet Hello!

I installed the `ms-vscode.hexeditor` and it **did** open a file via the hex editor. (<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> -> `View: Reopen Editor With ...` -> `Hex Editor`)

> Can you open both in parallel?

Do you mean like this? 👇 

<kbd>![スクリーンショット 2020-10-07 19 34 03](https://user-images.githubusercontent.com/11840938/95320223-257d7500-08d4-11eb-9aad-9d3e6b0e8229.png)</kbd>
<kbd>![スクリーンショット 2020-10-07 19 42 50_1200x](https://user-images.githubusercontent.com/11840938/95321104-88234080-08d5-11eb-9267-02a7f907d933.png)</kbd>

**Comment by hediet** [comment]
Ok, this is strange.
Can you open the webview dev tools (there is a VS Code command) while the drawio frame has focus and see whether there is any error message?

**Comment by jingyu9575** [comment]
Hi @hediet, I also see this issue on 1.0.0 / VSCode 1.49.3. It seems that none of the Draw.io scripts are loaded due to security restrictions. 

![图片](https://user-images.githubusercontent.com/8923139/95365356-9b013980-0904-11eb-878e-50cd1ede3009.png)

**Comment by KEINOS** [comment]
@hediet 

> Can you open the webview dev tools

<kbd>F1</kbd> -> type "`Open Webview Developer Tools`" and I get the similar `401 Unauthorized` msg with @jingyu9575 as below.

<kbd>![スクリーンショット 2020-10-08 13 40 55](https://user-images.githubusercontent.com/11840938/95415753-1b0eba00-096c-11eb-8efe-12a2c37eae07.png)</kbd>

- F.Y.I.
  - I've added the VSCode to the macOS Catalina's System Preferences in advance:
    - [ Security & Privacy ] -> [ Privacy ] -> [ Full Disk Access ]
  - I have NOT installed the desktop Draw.IO. Only the VS Code and the extension.
  - I have NOT asked to log-in nor select a repo in the initial boot after installing the extension.

**Comment by KEINOS** [comment]
I think I found a solution in my case.

- Uncheck the `Offline` settings of the extension.
  - Extension settings -> [`Hediet › Vscode-drawio: Offline`] -> [`When enabled, the bundled instance of Draw.io is used.`] -> Uncheck

<kbd>![スクリーンショット 2020-10-08 14 04 46](https://user-images.githubusercontent.com/11840938/95417464-14824180-0970-11eb-88a7-d4ffef73a04d.png)</kbd>

:tada:

<kbd>![スクリーンショット 2020-10-08 14 12 13](https://user-images.githubusercontent.com/11840938/95417615-73e05180-0970-11eb-9ca5-5e02a4c2dafd.png)</kbd>

So, it seems that it tries to use a bundled instance of Draw.io even online, isn't it?

**Comment by hediet** [comment]
Is this a mac only problem? I still cannot reproduce it in the most recent version of vscode (1.50) on windows.

@KEINOS the online-mode of draw.io offers much less features!

**Comment by hediet** [comment]
> So, it seems that it tries to use a bundled instance of Draw.io even online, isn't it?

Yes, and that should work. The online instance of Draw.io should only be used in emergencies.

**Comment by jingyu9575** [comment]
I just tested again on a new device. I've found that on my system, the issue is because VSCode's `data` directory is a symbolic link/junction. Unfortunately, the Scoop package installer creates the `data` directory this way. Probably VSCode's webview-resource protocol is not ready for this kind of configurations.

**Comment by KEINOS** [comment]
@jingyu9575 

Indeed! My current VSCode's data directory `~/.vscode` also was pointing to an external drive via a symbolic link!

I created a new user, installed only the `hediet.vscode-drawio`, and created a brand new file `sample.drawio` then I was able to open the **OFFLINE** draw.IO web view via the preview pane on the fly. No settings have been changed.

<kbd>![スクリーンショット 2020-10-12 14 15 36_1200x](https://user-images.githubusercontent.com/11840938/95708953-92a85600-0c98-11eb-8b7f-05bb0fa13ce1.png)</kbd>

So, I deleted the symbolic link of `~/.vscode` form the troublesome account, and moved all the files again under `~/.vscode` then it worked! Even the Offline extension setting is checked.

@hediet 

> Is this a mac only problem? I still cannot reproduce it in the most recent version of vscode (1.50) on windows.

Yep. So far, it seems to be a **macOS only problem** + `~/.vscode` path-dependent issue as @jingyu9575 pointed out. 

Maybe symbolic-linking the `C:\%HOMEPATH%\.vscode` might reproduce the issue as well on Windows10 but I don't have Windows10 now. Sorry.

One another thing that I noticed was that when this issue appears, it tries to open the web view straight away. Not when the `preview` icon was pushed.

- macOS Catalina (OSX 10.15.7), VSCode 1.50.0, `hediet.vscode-drawio` v1.0.1

**Comment by hediet** [comment]
Nice finding! Could you please open an issue in the vscode repository (as this error seems to be related to how web resources are handled)? A reproduction of this error with another extension would also he helpful.
I guess the pdf viewer extension might also use web resources.

**Comment by KEINOS** [comment]
Can't wait for the fix PR #152 of @jingyu9575 to be released!

@hediet 

> I guess the pdf viewer extension might also use web resources.

Do you have any extension in specific?

I tried the `tomoki1207.pdf` and `analytic-signal.preview-pdf` extensions but they did display the PDFs, even the `~/.vscode` was sym-linked.

**Comment by hediet** [comment]
> Can't wait for the fix PR #152 of @jingyu9575 to be released!

I just published it as insider build (1.0.201)!

> I tried the tomoki1207.pdf and analytic-signal.preview-pdf extensions but they did display the PDFs, even the ~/.vscode was sym-linked.

Apparently, I was wrong. This bug was actually specific to my extension!

**Comment by KEINOS** [comment]
> I just published it as insider build (1.0.201)!

:tada:

I confirm that `v1.0.2-alpha.1` (Draw.io Integration - Insiders Build 1.0.201, `hediet.vscode-drawio-insiders-build`) did fixed the issue in my env!

- `Vscode-drawio: Offline` -> checked
- `~/.vscode` -> sym-linked
- macOS Catalina (OSX 10.15.7), VSCode 1.50.0

@hediet  Thanks for the wonderful and great extension! and @jingyu9575 thanks for the great fix! You nailed it! 👍

**Comment by hediet** [comment]
@KEINOS thank you ❤️
