### ISSUE TITLE
Keyboard shortcut alt-shift-S

### ISSUE THREAD

**Issue by vgt** [hediet/vscode-drawio#144]
When I edit a drawio.svg and hit **alt-shift-S**, a dialog appears "Save diagrams to" and the edtior is gone.
It seems it is not possible to get back to drawio editor from there. The only option is to close the file.
* Saving the changes leads to an empty drawio.svg. Not having the file versioned in git or some otherway at that point is really bad.
* Not saving changes leads to all changes since the drawio.svg was last saved being lost.

For unsaved diagrams at app.diagrams.net, a similar behaviour occurs, but once the file is saved, the shortcut alt-shift-S does not work on app.diagrams.net anymore.
I am not sure, if this is an issue for drawio, or for this project.

**Comment by hediet** [comment]
Oh, thanks for finding this issue!
