### ISSUE TITLE
Add "New Draw.io Diagram" to the command palette

### ISSUE THREAD

**Issue by Alex-Mann** [hediet/vscode-drawio#145]
It would be very nice to add a shortcut to the command palette for "New Draw.io Diagram" which would save a <MYNAME>.drawio file to the current directory.

**Comment by jan25** [comment]
Could i help fix this?

**Comment by hediet** [comment]
@jan25 yes! Should be easy. I suggest a file save dialog + using vscode fs to create the file and then open the file.

**Comment by hediet** [comment]
Implemented with #155.
