### ISSUE TITLE
Unable to Switch Tab

### ISSUE THREAD

**Issue by arielaco** [hediet/vscode-drawio#15]
I switch tabs using Ctrl+Tab (workbench.action.nextEditor) and Ctrl+Shift+Tab (workbench.action.previousEditor) but it stops working once the drawio tab is focused.

**Comment by hediet** [comment]
That's hard to fix, unfortunately. Draw.io handles all key inputs and does not propagate them to VS Code. Also, Draw.io has a ton of custom keybindings that would be overriden by VS Code keybindings.

**Comment by hediet** [comment]
If this is super important, I can add a super hacky special case for it.

**Comment by arielaco** [comment]
Hey, thank you very much for reviewing it and coming back. In my case it isn't super important, appreciate you asking. I suppose I'd wait for other opinions. Take care.

**Comment by hediet** [comment]
Fixed in Insiders.
