### ISSUE TITLE
Cannot open .drawio.png files

### ISSUE THREAD

**Issue by vbridger** [hediet/vscode-drawio#151]
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..

Vscode Version: 1.50.0
Draw.io Integration Version: v1.0.1

**Comment by hediet** [comment]
Duplicate of #127.

**Comment by hediet** [comment]
Also possible duplicate of this:
https://github.com/microsoft/vscode/issues/108431
