### ISSUE TITLE
Failed to execute 'btoa' on 'Window'

### ISSUE THREAD

**Issue by wfireleaves** [hediet/vscode-drawio#158]
when I open my drawio.png file today, it not work.

`Unable to open 'scene.drawio.png': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..`

I have uninstall this plugin and reinstall it, not work again.

**Comment by hediet** [comment]
Is already fixed in vscode! Wait until they release their Bugfix.

**Comment by Xia-Ao** [comment]
do'not  use  chinese path
