### ISSUE TITLE
Export PNG images are blurred

### ISSUE THREAD

**Issue by banli17** [hediet/vscode-drawio#168]
![image](https://user-images.githubusercontent.com/12556069/96838311-533cef00-147a-11eb-9314-a3d53d87e00d.png)

When exporting to png, it becomes blurred

![image](https://user-images.githubusercontent.com/12556069/96838424-749ddb00-147a-11eb-81b4-a13fdbffcb9a.png)

**Comment by hediet** [comment]
Would be fixed by #114. Alternatively, use the svg export/conversion! Svg is always crisp.
