### ISSUE TITLE
Feature request: link nodes to files

### ISSUE THREAD

**Issue by sgaliamov** [hediet/vscode-drawio#169]
Thank you for creating this awesome extension!
At the first glance, I realized that this is what I have been looking for for a very long time.

The only one thing is missing. It's the ability to link nodes with files. It's like you do it for Code Link but much simpler. No need parse files or run a language server. Just click and file is opened. Drawio has the ability create a link to a path to facilitate this. Now it just does nothing. So it can be considered as a bag report ;)

Why do I need it. I have hundreds notes on my drive and managing them is a problem. I tried many notes organizers but all of them are sucks. Most of them do not support Markdown, local file storage, and tag management is not good enough. But if I will be able to draw releations diagram for notes, I don't need tags!

I believe it will be killer feature that will be able to compete with many note organizers!

PS. I've installed your extension for Crome. It's also awesome!

**Comment by hediet** [comment]
> It's like you do it for Code Link but much simpler. No need parse files or run a language server. Just click and file is opened.

Actually you can already do this!

Open your target file, then select a node in your diagram and press Shift+F3!
When you enable code link in the status bar and do a double click on the node, you jump to your target file.

It does not work with pdf files though, as the extension does not know which file is focused.

**Comment by hediet** [comment]
I added a context menu to files:

![image](https://user-images.githubusercontent.com/2931520/98484490-1d389280-2210-11eb-8b3e-17011c8b7a3e.png)

With it, you can link a node to any file.
If code link is enabled and you double click on a file, it opens the file.

**Comment by sgaliamov** [comment]
i had to install insiders build. but it works!
thank you very much!
