### ISSUE TITLE
Sync node label with linked file content

### ISSUE THREAD

**Issue by nopeslide** [hediet/vscode-drawio#172]
Enabling shape labels to be automatically updated when a linked file is changed.
This would be a huge benefit since it would open up a simple update functionality for draw.io diagrams.
Especially when writing markup/formulas the draw.io editor lacks editing functionalities, which could be mitigated.
Furthermore diagrams could be integrated in other automated workflows.

And it would be great for these upcoming diagram generators ;D

**Comment by hediet** [comment]
You mean by having node 123 linked to file "./my-content.txt" and the content of that file is `Hello World`, node 123 would also have `Hello World` as text?
And that file changes and node label changes are synchronized?

What happens if you open "./my-content.txt" and edit it, without opening the diagram?

Maybe the experimental feature "Edit nodes as text" is what you want?
What is your usecase?

**Comment by nopeslide** [comment]
> You mean by having node 123 linked to file "./my-content.txt" and the content of that file is `Hello World`, node 123 would also have `Hello World` as text?
> And that file changes and node label changes are synchronized?
> 
yes exactly

> What happens if you open "./my-content.txt" and edit it, without opening the diagram?
> 
it won't be updated, seems controversial at first, since it is not the "full experience", but if you want it updated you need to regenerate the diagram.
Would also not break draw.io compatibility.
 
> Maybe the experimental feature "Edit nodes as text" is what you want?
>
don't know this feature, but it sounds like a one-time behaviour, was thinking of permanent updates.

> What is your usecase?
>
I use draw.io often to generate RTL related graphics including annotations of toolchain results.
I always need to update the annotations by hand, but they could be easily extracted by a script and written to a file to be accessible by this proposed feature.
This is a lot of work if you have many of these annotations.

**Comment by hediet** [comment]
I can imagine an "Export Labels To JSON" / "Import Labels From JSON" command.
It would use the default node id to set/read the label.

Would this fix your usecase?

**Comment by nopeslide** [comment]
that would fix the annotation problem and seems like an good generic approach.
the json could also be used as mapping to file contents like
```json
{
  "node1": {"string":"new label"},
  "node2": {"file": "node2.txt"}
}
```
this could become an interface for automation, very nice idea.

**Comment by hediet** [comment]
I don't see why such a json file should be able to reference files.
If you can already automate creating/updating such files, you should easily be able to create the full json file instead. What do you think?

> if the json has the same path/name as the diagram, it could also be found without specifying anything.
maybe making even code linking possible? :D

I try to avoid such implicit semantics. You could bind a hotkey to the "import from json" command that already inserts a (static) filename.

**Comment by nopeslide** [comment]
> I don't see why such a json file should be able to reference files.
> If you can already automate creating/updating such files, you should easily be able to create the full json file instead. What do you think?
> 
manipulating json requires an additional stack of tools I wanted to avoid and
there would be no difference to just manipulating the xml itself (which I also wanted to avoid).

> I try to avoid such implicit semantics. You could bind a hotkey to the "import from json" command that already inserts a (static) filename.
>
fair enough

What do you think about exposing your extensions configuration (color maps, code linking, ... ) also in this json config?

**Comment by hediet** [comment]
> manipulating json requires an additional stack of tools I wanted to avoid

It is much easier to generate json than to manipulate xml.
[You can use `jq` to generate the json from the command line](https://stackoverflow.com/questions/48470049/build-a-json-string-with-bash-variables).

Tools should be composable and not an all-in-one solution. I think JSON is easy enough for use as an interface.

> What do you think about exposing your extensions configuration (color maps, code linking, ... ) also in this json config?

What is wrong with the VS Code workspace/dir config?
If you use the global vs code settings, they are even synchronized across machines if you want.

My philosophy is to implement just the minimal amount of features to enable the best user experience.

**Comment by nopeslide** [comment]
> What is wrong with the VS Code workspace/dir config?
> If you use the global vs code settings, they are even synchronized across machines if you want.

they apply for all diagrams in a workspace/dir and not per diagram.
I was reminded of the png issue and the per diagram settings problem.

**Comment by nopeslide** [comment]
I think a draw.io plugin would be better for this,
because of the missing headless export in the your extension.

@hediet 
I just need a pointer how to get the current filepath in your extension.
In the electron version I can query `App.currentFile`,
but as far as I see you pipe the file through the event message system?

**Comment by hediet** [comment]
You cannot access the current file Uri right now I think. Feel free to open a PR to fix this! Maybe I can have a look later.

**Comment by nopeslide** [comment]
> You cannot access the current file Uri right now I think. Feel free to open a PR to fix this! Maybe I can have a look later.

no worries. just noticed you pass it via the `DocumentContext` when loading plugins.

**Comment by hediet** [comment]
I think for now, a custom plugin might be better for you.
If this issue receives enough upvotes or this feature is really important for you, I can reprioritize it!

**Comment by nopeslide** [comment]
would also prefer the drawio plugin variant,
because it only makes sense if integrated in some headless workflow and that ain't possible with your extension.
When I find the time I will create the plugin under the name `vscode-drawio-plugin-automation`.
