### ISSUE TITLE
update please vscode for open-vsx.org

### ISSUE THREAD

**Issue by AS400JPLPC** [hediet/vscode-drawio#173]
please :
is possible update https://open-vsx.org/extension/hediet/vscode-drawio  999.0.0-alpha different https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio 1.03

thank-you   sorry my english

**Comment by hediet** [comment]
It is updated, but the higher version prevents the update from being considered.
[This](https://github.com/eclipse/open-vsx.org/issues/205) will fix it.
