### ISSUE TITLE
The extension is breaking previous search match SHIFT-F3

### ISSUE THREAD

**Issue by xoofx** [hediet/vscode-drawio#176]
I noticed that the extension is breaking the search previous (SHIFT-F3 on windows) with a `command 'hediet.vscode-drawio.linkCodeWithSelectedNode'` not found:

![image](https://user-images.githubusercontent.com/715038/97774279-9112d500-1b56-11eb-9a8d-92358ae01392.png)

This happen on a any documents, including not related to drawio

**Comment by hediet** [comment]
Can you try the insiders build?
This particular issue should be fixed there.

**Comment by xoofx** [comment]
Yep, just checked and it is fixed, thanks!
