### ISSUE TITLE
SVG Border

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#179]
it would be great to be able to set a border of 10/20 px as default when saving as svg

_Originally posted by @mike-asm in https://github.com/hediet/vscode-drawio/pull/178#issuecomment-725028912_

**Comment by coolbreeze413** [comment]
It would be great for export as png too. This seems to be the only thing missing for which I am seeing a nees to open the standalone app or the browser app.

**Comment by hediet** [comment]
See #194. This feature is available now with the latest insiders build!
