### ISSUE TITLE
Not able to export as pdf

### ISSUE THREAD

**Issue by sannamalai176** [hediet/vscode-drawio#18]
when i try to export as pdf or any other type of document, option is not working in vscode

**Comment by hediet** [comment]
I think I will not implement this soon, as it requires much work and is a very specific feature. You can always use the Desktop App to export your diagrams as pdf!
I'll try to hide the menu item though.
Also, you could save your diagram as svg (simply rename it to `{name}.drawio.svg`) and print this svg to pdf using your favourite tool.

**Comment by Queuecumber** [comment]
I'm curious what exactly the blocker is on various export options? Is there a reason the entire "export" feature from the desktop app can't be used as-is?

**Comment by hediet** [comment]
I think it uses electron APIs that are not exposed to VS Code extensions.
