### ISSUE TITLE
[Virus report] - ClamTk found "PUA.Html.Trojan.Agent-37075" 

### ISSUE THREAD

**Issue by dalerka** [hediet/vscode-drawio#184]
Hey! Today the ClamTk virus scan (on MX Linux 18.3 x64) reports:

../.vscode/extensions/hediet.vscode-drawio-1.1.0/dist/extension/index.js                                                          PUA.Html.Trojan.Agent-37075

**Comment by hediet** [comment]
Thanks for this issue. That index.js file bundles quite a few libraries. What do you suggest to do about it?

**Comment by dalerka** [comment]
I'd suggest checking the dependencies for viruses. In particular, the very popular `imurmurhash` package has a virus as reported here:
https://github.com/jensyt/imurmurhash-js/issues/1 
Note that the ClamTk found the Trojan in the minified version.

**Comment by hediet** [comment]
This is not a commercial project and thus I have not the man-power to investigate this issue more thoroughly.
Most probably this is a false positive report by ClamTk.

If I accidentally bundled a virus, which is highly unlikely, I'm very sorry - it is up to you to use this extension.
Please check the `package.json`/`yarn.lock` file to see which npm packages I'm using. Most of them are pretty popular packages.

**Comment by devHk0Matsu4zkrei** [comment]
Sep 8 2024 I did the last update in clam tk and still reported as potential unwanted program  PUA.Win.Trojan.Xored-1  Xored-1 seems a possible spies behave.

**Comment by hediet** [comment]
For more context see here: https://github.com/jensyt/imurmurhash-js/issues/1
-> this really are false positives.
