### ISSUE TITLE
drawio.png file is ambiguous when open in picture browser with many components in it

### ISSUE THREAD

**Issue by xshrim** [hediet/vscode-drawio#188]
When there are many components in the drawio.png file, it is very 
ambiguous to open in the picture browser(although it is clear when editing), and the file size is relatively small. But if open it in the online draw.io and set a larger zoom ratio when exporting, the picture can be clearer, and the file size will be much larger.

![image](https://user-images.githubusercontent.com/19187371/101720927-c8738a80-3ae1-11eb-9018-648b03e834e8.png)

So is it possible to set the default zoom ratio when saving in the vscode settings?

**Comment by hediet** [comment]
This is supported now in the insiders build! See #194.
