### ISSUE TITLE
side by side xml

### ISSUE THREAD

**Issue by tkinz27** [hediet/vscode-drawio#19]
Hoping I just need to save my document in a specific way, but when I hit reopen as and choose text editor, I get an xml document with a single element `<diagram>`. It seems to me that the string in the `<diagram>` is some sort of base64 encoded element. Any ideas what I'm doing wrong?

**Comment by hediet** [comment]
What exactly are you doing? Can you post screenshots? Thanks ;)

**Comment by tkinz27** [comment]
So I have been splitting the window, duplicating the editor. Then in one of the editors, I open the command pallate and do `Repoen with` and click the text editor.

![image](https://user-images.githubusercontent.com/3259664/81742039-53a97680-9454-11ea-909f-f60ff8e116ab.png)

**Comment by hediet** [comment]
Oh I can confirm it. It used to work in a previous version.
