### ISSUE TITLE
*.drawio.png files can not open 

### ISSUE THREAD

**Issue by 0clickjacking0** [hediet/vscode-drawio#192]
Hello developer,I meet a problem that I can't open any ext is png files. example test.drawio.png.When I open the file in vscode,just like this

![](http://images.xianyu123.club/20210108191515.png)

**Comment by hediet** [comment]
Hey, did you install the Draw.io extension successfully? Doesn't look like the Draw.io extension is triggered to load the png file. This is just the default VS Code image viewer.
Also, the png file seems to be corrupted...

**Comment by 0clickjacking0** [comment]
> Hey, did you install the Draw.io extension successfully? Doesn't look like the Draw.io extension is triggered to load the png file. This is just the default VS Code image viewer.
> Also, the png file seems to be corrupted...

the picture is here http://images.xianyu123.club/20210108191515.png,I don’t know why github is not loaded here, the plugin I installed is https://marketplace.visualstudio.com/items?itemName=eightHundreds.vscode-drawio

**Comment by 0clickjacking0** [comment]
> Hey, did you install the Draw.io extension successfully? Doesn't look like the Draw.io extension is triggered to load the png file. This is just the default VS Code image viewer.
> Also, the png file seems to be corrupted...

the picture is here http://images.xianyu123.club/20210108191515.png   ,I don’t know why github is not loaded here, the plugin I installed is https://marketplace.visualstudio.com/items?itemName=eightHundreds.vscode-drawio

**Comment by hediet** [comment]
That is not my draw.io extension. Please open an issue at their repository.
