### ISSUE TITLE
[Bug report] Strange behavior of the [Arrange/Distribute] function

### ISSUE THREAD

**Issue by YTHsieh** [hediet/vscode-drawio#193]
Hello, thanks a lot for this nice extension.

I'm not sure whether this is a bug. When I use the [Arrange/Distribute] function in the toolbar, the result of alignment seems strange.

![image](https://user-images.githubusercontent.com/31568940/104082746-815cee80-5273-11eb-97d6-cbb8250b5cd0.png)

Just like the image above. The rectangles selected are not spread in an identical spacing.
I met this scenario when the number of selected objects is more than 3.

**Comment by hediet** [comment]
You need to select "Distribute / Horizontal" to get identical spacing!
