### ISSUE TITLE
Support "Properties" menu option when editing PNG

### ISSUE THREAD

**Issue by collinwright** [hediet/vscode-drawio#194]
The official draw.io app has a handy "Properties" button in the "File" menu that allows you to set the "Zoom" and "Bordor" for PNG documents while editing them. This is very handy for ensuring that the PNG stays at a reasonable size with nice negative space. Including this support would make the draw.io extension perfect for editing diagrams along with Markdown in VS Code for me :-)

**Comment by hediet** [comment]
Support for zoom & border is planned!

Have you considered using *.drawio.svg files instead? They work on github and in markdown files too and look much better!

**Comment by collinwright** [comment]
SVG support is excellent, but unfortunately, it doesn't render correctly inside Markdown in GitLab  :-(

Is the "Properties" support (which saves Zoom & Border to the file, so that subsequently opening the file retains these settings, and the PNG always saves at the correct zoom) inherent to supporting zoom/border, or would that need a separate effort?

**Comment by hediet** [comment]
> it doesn't render correctly inside Markdown in GitLab :-(

Do you know why? 

> Is the "Properties" support (which saves Zoom & Border to the file, so that subsequently opening the file retains these settings, and the PNG always saves at the correct zoom) inherent to supporting zoom/border, or would that need a separate effort?

I don't know yet how to implement this whole feature. I know that I can set a zoom factor when exporting the PNG, but I don't know if and how Draw.io persists a zoom level per diagram.
A diff of draw.io diagrams with different property settings but otherwise equal content would be interesting.

I guess I should allocate some weekend to implement this ;)

**Comment by hediet** [comment]
I added a new "Properties" dialog that lets you configure a `scale` and a `border` value! It affects both `SVG` and `PNG`.
