### ISSUE TITLE
plugin packaged from sourcecode is unused

### ISSUE THREAD

**Issue by qibo-cn** [hediet/vscode-drawio#197]
`vsce package`

packaged plugin from source code, but after install the plugin into vscode, when open a .drawio file, 
![image](https://user-images.githubusercontent.com/17426311/104992818-c562a700-5a5c-11eb-88e4-63848aeb22ea.png)
that picture showing

**Comment by hediet** [comment]
Could you fix it?

**Comment by qibo-cn** [comment]
> Could you fix it?

yeah, I forgot update submodule of darwio,

thanks
