### ISSUE TITLE
[feature request] Support change language

### ISSUE THREAD

**Issue by eightHundreds** [hediet/vscode-drawio#20]
I'm curious why your extension can't load these two areas.

![image](https://user-images.githubusercontent.com/18695431/81643219-b6e8d800-9457-11ea-81a6-57656580dde0.png)

![image](https://user-images.githubusercontent.com/18695431/81643240-c0724000-9457-11ea-8910-0ff25867d619.png)

**Comment by eightHundreds** [comment]
In my impression , scratchpad will storage in localstorage ,but webview cannot persist localstorage.

so you should listen "configure" event, and then sync to `context.workspaceState`

**Comment by hediet** [comment]
@eightHundreds Thanks for your input! And for linking me in your readme ;)
I'll see what I can do there. The language should be the same as the current VS Code language though.

**Comment by hediet** [comment]
I'll close this issue in favor of #23 and #24.
