### ISSUE TITLE
Exported "sketch" styled diagrams to .png barely readable

### ISSUE THREAD

**Issue by MikhailZex** [hediet/vscode-drawio#200]
The shading on exporting `.drawio` files with the "sketch" style enabled to `.png` renders them unreadable. It would help to enable solid fills for sketch-styled diagrams by default or provide a way to global edit the fill of all shapes at once.

I realize that the suggestions might not be practical/doable -  I don't know to what extent drawio is configurable so, feel free to ignore this.

That being said, just discovered your extension today and I. AM. BLOWN. AWAY. Very helpful. Thanks!

![trial](https://user-images.githubusercontent.com/52100648/106042676-63acd780-6103-11eb-8b91-ed688e315877.png)

**Comment by hediet** [comment]
Thank you!

Can you describe what you find unreadable? I find your diagram quite readable (github light theme if that matters - it seems like the diagram uses some transparent values).
Does this issue only happen when exporting the diagram to png files?

**Comment by MikhailZex** [comment]
Wow. OK. It was the dark theme ( I use dark theming everywhere possible).

I noticed that you can set the background fill of individual shapes to transparent (or essentially turn off shape backgrounds) - that ensure that exported diagrams render cleanly on dark themed UI. Individually changing the background of each shape is tiring, if there was a way to globally edit the bg, the job is much simpler.

when you don't turn off the bg fill, this is how things end up looking on dark mode 👀 
![image](https://user-images.githubusercontent.com/52100648/106051647-b93ab180-610e-11eb-8479-46cd6a4fbedf.png)

**Comment by hediet** [comment]
I guess the Draw.io desktop app will have the same problem.
Probably this is not that easy to fix and is more of a Draw.io problem that a problem with this extension.

Btw. you can easily change the draw.io theme used by the extension in the status bar!

**Comment by MikhailZex** [comment]
I kinda like the plain uncolored wireframe-ish diagrams and the other themes are colored \*sigh\*.

Well thanks for your time.
