### ISSUE TITLE
Documentation for "Editing the Diagram and its XML Side by Side"

### ISSUE THREAD

**Issue by clayms** [hediet/vscode-drawio#207]
Fantastic plugin!

Not sure if VS Code changed, but to open the Diagram and its XML Side by Side, the command I have to enter is <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> then `View: Reopen Editor With...` not `File: Reopen With...` as shown in:
https://github.com/hediet/vscode-drawio/blob/master/README.md#editing-the-diagram-and-its-xml-side-by-side
and
https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio#editing-the-diagram-and-its-xml-side-by-side

Extension version: 1.3.0
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.13GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Chapi15** [comment]
I have the same issue, when I try to open the XML file and its Diagram side by side the command `View: Reopen Editor With ...` does not appear; perhaps in one of the VS Code updates it was deprecated 

* Extension Version: 1.4.0
* VS Code Version: 1.54.3
* OS Version: Darwin x64 19.6.0 - MacOS Catalina

**Comment by hediet** [comment]
This works for me:

![image](https://user-images.githubusercontent.com/2931520/112339501-032fb600-8cc0-11eb-8865-f4d1b28a5bcd.png)

![image](https://user-images.githubusercontent.com/2931520/112339546-0c208780-8cc0-11eb-93f5-2164c99b7b85.png)


> I have the same issue, when I try to open the XML file and its Diagram side by side the command View: Reopen Editor With ... does not appear; perhaps in one of the VS Code updates it was deprecated

This sounds like a VS Code bug.

I updated the readme to reflect the new name.
