### ISSUE TITLE
New line xml character (&#xa;) is added to .drawio file xml when working with multiple pages

### ISSUE THREAD

**Issue by TomMalow** [hediet/vscode-drawio#209]
I have an issue when working on a .drawio file that contains multiple pages. 

When opening the file and opening one of the pages, then all other pages than the first page and the page I have opened are modified in the xml structure with a new line character, '&#xa;', for each line in the page xml section:

```xml
<mxGraphModel dx="886" dy="722" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
    &#xa;
    <root>
        &#xa;
        <mxCell id="PVPVOHK6S1uZNFgAj0cW-0"/>
        &#xa;
        ...
```

Opening an affected page will remove the new line characters again. Meaning that I have to make sure to open all pages each time I modify the file to avoid cluttering the xml with new line characters. 

This also causes issue if the diagram is part of a git repo as a small change to a single page can produce a large commit, for the entire file. Cluttering git history and producing merge conflicts that can't be auto-resolved.

Video displaying the issue:

https://user-images.githubusercontent.com/13435947/108323977-9f4d3580-71c7-11eb-91ff-2cfaed63dae4.mp4

# System Information
Extension version: 1.3.0
VS Code version: Code 1.53.2
OS version: Windows 10 Enterprise x64 10.0.19042 Build 19042

**Comment by hediet** [comment]
Unfortunately, this seems to be a draw.io issue.
The draw.io extension formats the XML on save to make it diff'able. Draw.io does not seem to like the whitespace in combination with with multiple pages (???).

I can offer these hacky fixes:
* a) Delete all `&#xa;`, then format the xml after saving.
* b) A VS Code Setting to enable a) (by default disabled).
* c) Unformat the xml before sending it to Draw.io.
* d) Add an option to disable formatting entirely.

a) Might accidentally delete significant `&#xa;`. I don't know if there are significant `&#xa;` though, as newlines are encoded differently in attributes. Is very easy to implement though.
b) Is less risky by disabling a) by default. This bug does not seem to affect many people, given that it is only reported now. If it affects someone, they can toggle that setting on demand.
c) Might be the best solution, but is not that easy to implement.
d) Has the least risk, but it won't make diff'ing any easier.

Probably I will try c) for some time and if it does not work fall back to b).
What do you think?

**Comment by TomMalow** [comment]
Had my suspicion that it might Draw.io, but great to hear that there are some options for resolving it.

a)+b) is the easiest but that will only resolve the issue on any given user that has it enabled. Another collaborator might not have that option set and thereby introducing whitespace again. Additionally, a) it might remove too much as you said.

However, I am the only one who have reported it and currently we don't have that much collaboration on diagrams for now. So a hacky solution is fine for me atm.

Agree that c) is the correct solution. But I leave it up to decide which makes sense to implement.

Great extension btw.

**Comment by hediet** [comment]
I found a much easier solution. Should be fixed in the current insider release.

**Comment by TomMalow** [comment]
That looks like a simple solution. Looking forward to the upcoming release!

**Comment by hediet** [comment]
This fix should be available already in the latest stable release!
