### ISSUE TITLE
Add file icon for drawio files

### ISSUE THREAD

**Issue by ramank775** [hediet/vscode-drawio#21]
Presently, drawio file doesn't have it's icon associated to it. 
![image](https://user-images.githubusercontent.com/24293550/81648165-de39a800-944b-11ea-97ef-dda6147470fc.png)

Add a new file icon mapping for drawio files

**Comment by ramank775** [comment]
It seems like currently vscode is not supporting adding new fileIcons. There is issue already reported https://github.com/microsoft/vscode/issues/14662

**Comment by hediet** [comment]
Thank you very much for looking it up!

**Comment by hediet** [comment]
[The Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) has icons for *.dio and *.drawio files:

![image](https://user-images.githubusercontent.com/2931520/86044242-220f5d80-ba4a-11ea-9fa5-cff17f59bff8.png)
