### ISSUE TITLE
Does not refresh view of template.drawio on Mac OS X

### ISSUE THREAD

**Issue by john-aws** [hediet/vscode-drawio#212]
New user of v1.3.0 and I have cfn-dia 1.1.20. Running on Mac OS X Mojave with VS Code 1.54.1.

I have cfn-dia running in a VS Code terminal and have opened template.drawio in VS Code. When I make a filter change using cfn-dia, e.g. to filter out Elastic IPs, cfn-dia writes a new template.drawio file (it has new timestamp and has different size) but most of the time vscode-drawio does not refresh the view of that template. It seems that only the very first change made to template.drawio is detected by vscode-drawio, but all subsequent changes are ignored.

Related: [How do you get out of the cfn-dia menu?](https://github.com/mhlabs/cfn-diagram/issues/32)

**Comment by john-aws** [comment]
Confirmed this is 100% reproducible on my Mac.

I also note that when attempting to close the drawio template view in VS Code, I am prompted "Do you want to save the changes you made to template.drawio?" I mention this in case it's relevant information. I did not make any changes using the embedded drawio editor though cfn-dia made changes to template.drawio under the covers, but I would not expect to be prompted to save something that I had not changed.

**Comment by hediet** [comment]
Yeah, I observe the same bug from time to time, however, I didn't manage to make it reproducable on windows.

Can you try out the insiders build? Afaik I changed some logic there regarding this.

**Comment by john-aws** [comment]
I tried the vscode-drawio v1.4.3 insiders build (with VS Code retail build), and it had the same problems. It refreshed after the first change but not any subsequent change.

I also tried the vscode-drawio v1.4.3 insiders build (with VS Code insiders build), and it was actually more problematic. It didn't refresh after the first change or any subsequent change.

**Comment by hediet** [comment]
Should be fixed by 74e06925.
