### ISSUE TITLE
Code link not working, mac os

### ISSUE THREAD

**Issue by msab** [hediet/vscode-drawio#216]
I've enabled code link and have the text editor open split down from the draw.io diagram. I click on a draw.io node and the xml does not jump to its tag.

Not sure if this is what the code link is for?

Thanks,

Michael

**Comment by hediet** [comment]
Code links are to jump to associated source code (eg TypeScript), not to jump to the corresponding xml code of the node.

**Comment by msab** [comment]
Understood, thank you.
