### ISSUE TITLE
CTRL+TAB is not working

### ISSUE THREAD

**Issue by erayerdin** [hediet/vscode-drawio#219]
I frequently use CTRL+TAB to switch to most recent tab, but when I switch to a draw.io tab, I can't switch back to the other tab. This is the issue.

**Comment by hediet** [comment]
Does this still happen? I cannot reproduce it with latest VS Code / Draw.io on Windows.

**Comment by erayerdin** [comment]
I tried it again and it seems like the issue is gone. That's strange. It's resolved in my case.

**Comment by hediet** [comment]
Thanks for checking it again!
