### ISSUE TITLE
Hide Export Options

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#22]
#18

**Comment by devKyanon** [comment]
If the extension just provides a link generated from the export menu (i.e., download button) as an external link, wouldn't it be possible to import the export via VSCode? 

(I am not good in this area. I just hope I can export my figures to PDF in VScode)

**Comment by hediet** [comment]
I guess draw.io does some black pdf magic there, that just does not work in Electron (VS Code).
Feel free to investigate though!

Why do you want to export to pdf anyways?

**Comment by devKyanon** [comment]
I am a Ph.D candidate and I use VScode to write my paper (using Latex workshop). 

When I draw figures, vector images are preferred, and PDF images are one of the best solutions for latex. Many researchers use this latex and pdf images combination.

Previously, images were converted to pdf using an external tool (In my case, I use Omnigraffle), but it would be very convenient if all working environments could be integrated into VScode!

**Comment by devKyanon** [comment]
Apart from writing papers, I think many people also need vector images for high-resolution images, and the pdf export may be an important feature to them.

**Comment by devKyanon** [comment]
Anyway, I very very very love your extension and fall in it! :) 
Thank you for your contribution!!

**Comment by hediet** [comment]
[For my bachelor thesis](https://github.com/hediet/bachelors-thesis), I too used drawio + Latex. Svg actually worked way better than pdf! I remember that the drawio pdf export had problems, I don't remember the specifics though.

**Comment by hediet** [comment]
[I actually was able to use the math mode in SVG](https://github.com/hediet/bachelors-thesis/blob/master/images/NakamuraZeit.svg).
This is a screenshot of the pdf:
![image](https://user-images.githubusercontent.com/2931520/81698423-40070b80-9466-11ea-993a-8742a1e61bd6.png)

**Comment by hediet** [comment]
Haha, I just checked out my bachelor thesis:

![image](https://user-images.githubusercontent.com/2931520/81699410-9759ab80-9467-11ea-8424-c428a7cdd98e.png)

Now I'm in love with my extension too :D

**Comment by hediet** [comment]
Fixed in v0.4.0.
