### ISSUE TITLE
Copy-pasting between files doesn't work

### ISSUE THREAD

**Issue by FooBarWidget** [hediet/vscode-drawio#220]
Thanks for this very useful extension!

Copy-pasting within a file works, but copy-pasting between files doesn't. It looks like copying doesn't use the OS' clipboard, but instead uses some internal clipboard.

I'm on macOS.

**Comment by hediet** [comment]
I cannot reproduce your issue on Windows 😕

**Comment by FooBarWidget** [comment]
Now I can't reproduce this issue anymore either. 🤔
