### ISSUE TITLE
Change PNG resolution

### ISSUE THREAD

**Issue by StefanFabian** [hediet/vscode-drawio#222]
First of all, thank you for your work on this extension.
This extension saves me quite a bit of time.
However, I was wondering how you can specify the resolution of the exported PNG.
Is there any way to change that?

**Comment by hediet** [comment]
Thanks!
You can set a zoom level that influences the resolution for the png export:
![image](https://user-images.githubusercontent.com/2931520/117130965-12b31c00-ada1-11eb-8a25-81c568c4b2bc.png)

**Comment by StefanFabian** [comment]
Ah thank you!
For anyone looking for this in the future, the export properties are located at File > Properties
