### ISSUE TITLE
VS Code 1.56 update breaks SVG association

### ISSUE THREAD

**Issue by alexandervnuchkov** [hediet/vscode-drawio#223]
Thank you for a great extension!

Looks like VS Code 1.56 update breaks the association of the extension with the SVG files via `workbench.editorAssociations` and they start to open like text XML files only. Opening *.drawio.svg works alright.
I downgraded to 1.55.2 and the SVG files started opening again as image files.
It might be related to the https://code.visualstudio.com/updates/v1_56#_default-custom-editor-and-notebook-resolution feature in version 1.56, I couldn't find the way to make VS Code 1.56 open SVG files as images.
My system: Kubuntu 20.10, VS Code 64-bit version.

**Comment by felixjulianheitmann** [comment]
Just to confirm I have the same issue, on Windows and in my Docker environment, VS Code 64-bit and VS Code Insider 64-bit.
For the insider I used the apperently different association syntax

`
"workbench.editorAssociations": {
    "*.svg": "hediet.vscode-drawio-text",
},
`

**Comment by hediet** [comment]
I'm sorry, I cannot reproduce your issue in the latest VS Code insider.

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Can you try it also with the latest insider?

**Comment by alexandervnuchkov** [comment]
The latest VS Code inside does fine with the latest hediet.vscode-drawio-insiders-build (1.4.3):
Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:51:40.777Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-17-generic

But the current stable VS Code still breaks the *.svg associations with either hediet.vscode-drawio (1.4.0) or hediet.vscode-drawio-insiders-build (1.4.3):
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-17-generic

**Comment by hediet** [comment]
Then it is vscode bug that is already fixed! It will work for the next stable too.
