### ISSUE TITLE
How to close left (parts) panel? 

### ISSUE THREAD

**Issue by robcca** [hediet/vscode-drawio#225]
Than you for this great extension. The only complaint I have is that I can't find any way to close the left panel. I looked in the menu for such an option. Dragging the resize bar all the way to the left isn't permanent and the panel will spring open again for no obvious reason when I'm moving the mouse. Might it be possible to include this option if I'm somehow over-looking it?

**Comment by robcca** [comment]
Oh! I just found a button at the far right of the window that does the job; it looks like a "full screen" icon. All the same, a similar control might be placed near the left panel to make it easier to find. I'll close this issue now.

**Comment by hediet** [comment]
Thanks for reaching out!

This extension basically embeds the Draw.io UI as is. I guess your input also applies to the web and desktop-version of Draw.io, so I think it makes sense to discuss this in the official Draw.io repository!
