### ISSUE TITLE
Is it possible to adjust the language?

### ISSUE THREAD

**Issue by dasu88** [hediet/vscode-drawio#231]
The language currently displayed is not my default language, is it possible to adjust it?

**Comment by hediet** [comment]
Which language do you use in VS Code? Which language do you want to use in draw.io?

**Comment by dasu88** [comment]
> Which language do you use in VS Code? Which language do you want to use in draw.io?

I am using Traditional Chinese, but it only shows Simplified Chinese, which is not the usual language in Taiwan

**Comment by hediet** [comment]
Does [draw.io](http://draw.io) offer this language?

**Comment by dasu88** [comment]
![2021-06-09_181045](https://user-images.githubusercontent.com/23251263/121336627-4956f600-c94e-11eb-8a40-688c36cea1e1.jpg)
Yes, at the bottom of the language menu

**Comment by hediet** [comment]
Can you investigate what `require("vscode").env.language` is for you? Or even better, can you do a PR? Thank you!

**Comment by dasu88** [comment]
![2021-06-09_182602](https://user-images.githubusercontent.com/23251263/121338802-72788600-c950-11eb-9978-7c8a8cd4af32.jpg)
I don't quite understand what you mean, but my vscode displays the language as above

**Comment by hediet** [comment]
Can you please verify that it works now in the Insiders Build? https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio-insiders-build

Thanks!

**Comment by dasu88** [comment]
Yes, it is currently showing my language correctly, thanks for your help
