### ISSUE TITLE
Cant open drawio files on linux ubuntu 20 with vscode 

### ISSUE THREAD

**Issue by 21kc-caracol** [hediet/vscode-drawio#237]
I am running on linux ubuntu 20 with vscode 1.57.1:

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic snap

When trying to open a *.drawio file i get the following error:

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

Thanks...

**Comment by hediet** [comment]
I think this is due to https://github.com/microsoft/vscode/issues/122951.

**Comment by 21kc-caracol** [comment]
The previous error disappeared after downgrading to:

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-55-generic snap

but now it shoes just xml data and not the drawings.

**Comment by hediet** [comment]
Can you use the Luna Paint extension?

**Comment by 21kc-caracol** [comment]
I installed the extension, saved a regular screenshot in a projects' folder, and tried to open it through vscode, but it opened as a binary file, and I didn't see any Luna Paint options to open it differently. Moreover, the image isn't visible in the Explorer of the vscode project

**Comment by hediet** [comment]
If Luna Paint also does not work, it really seems to be https://github.com/microsoft/vscode/issues/122951.

**Comment by 21kc-caracol** [comment]
I'm sorry I'm new to understanding issues through this platform, what do you mean? that this is something that Microsoft needs to resolve in future versions of vscode and that it is not something "the extension" can do to solve? (I've read the link you shared).

**Comment by hediet** [comment]
> that this is something that Microsoft needs to resolve in future versions of vscode and that it is not something "the extension" can do to solve? (I've read the link you shared).

Unfortunately, yes.

**Comment by hediet** [comment]
I'm closing this issue as it does not seem to be specific to this extension.

**Comment by eduncan911** [comment]
As an update to #122951 ... They have made it even more confusing by separating Windows users from Linux users (and removing the Linux label).

So, if on windows: https://github.com/microsoft/vscode/issues/125951

If on Linux, go here: https://github.com/microsoft/vscode/issues/125993
