### ISSUE TITLE
Use Current User Language from VS Code in Draw.io

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#24]
Currently, the Draw.io interface is always English.

**Comment by WuhenPhi** [comment]
Hello, Drawio supports a lot of languages, so does the [vscode-drawio](https://github.com/eightHundreds/vscode-drawio) . I dont know why this cannot with a higher version of drawio. So please  add  support for changing language. Thanks a lot.
English is not very well, hope you can understand.

**Comment by WuhenPhi** [comment]
> Currently, the Draw.io interface is always English.

Hello, Drawio supports a lot of languages, so does the [vscode-drawio](https://github.com/eightHundreds/vscode-drawio) . I dont know why this cannot with a higher version of drawio. So please  add  support for changing language. Thanks a lot.
English is not very well, hope you can understand.

**Comment by hediet** [comment]
Ah I see, he is using an older version of drawio! I'll investigate this soon!

**Comment by hediet** [comment]
Fixed in v0.4.0.
