### ISSUE TITLE
Allow code link to recognise templated classes in C++

### ISSUE THREAD

**Issue by bartasha** [hediet/vscode-drawio#240]
The code link feature does not currently match C++ classes that are templated.  I believe adding the following characters to the match filter (link below) ought to allow templated classes to be matched: `<> ,` (Angled brackets, space and comma.)  Maybe worth making the filter text configurable to support different languages.

Might need someone better than me at using C++ templates to know whether this will cope with cases I haven't encountered.

https://github.com/hediet/vscode-drawio/blob/9e50322b017fae7db4c01a4b1ee304bea5a286a3/src/features/CodeLinkFeature.ts#L165

Awesome plugin though...

**Comment by hediet** [comment]
Thanks! If you do a PR and change the changelog accordingly, the new version of the extension gets published automatically!
