### ISSUE TITLE
consider merging into https://github.com/jgraph/drawio

### ISSUE THREAD

**Issue by anderskristian** [hediet/vscode-drawio#250]
This is a super application to "MS code"
At the same time I must admit that it is behind the drawio
Would it be possible to let jgraph/drawio have another target?

I'm sorry to see that many requests needs man-power

**Comment by hediet** [comment]
> At the same time I must admit that it is behind the drawio

It should not be behind draw.io - I'm regularly updating the shipped version of Draw.io.
Some functionality of Draw.io is excluded in this extension as it is just broken inside a VS Code webview.

> I'm sorry to see that many requests needs man-power

A lot of the help-wanted issues are features for a very specific use-case and often not even offered by draw.io itself.

> Would it be possible to let jgraph/drawio have another target?

I doubt it is that easy.
