### ISSUE TITLE
Drawio Plugins - JavaScript `require` Calls

### ISSUE THREAD

**Issue by ZachsPage** [hediet/vscode-drawio#252]
Hello! When attempting to load `.js` Drawio plugins, it seems any `require` calls cause the plugin to fail - like these, for example:
```
const path = require('path');
const fs = require('fs');
```
The above example comes from my Drawio plugin which allows users to link to other Drawio files from within a diagram (https://github.com/ZachsPage/drawio-plugin-local-links - actually just saw someone requesting this feature in your repo's "issues" https://github.com/hediet/vscode-drawio/issues/94). I removed the `require` calls and any of those modules' functions, then the plugin loaded successfully (before this, the plugin's additional right-click options were not being added).

I tried this on Windows, loading the plugin with the VSCode setting:
```
"hediet.vscode-drawio.plugins": [
        { "file": "<Path to my repo clone>\\src\\locallinks.js"}
    ],
```
The module functions could be implemented within the plugin, but I think supporting Drawio plugins that have `require`s in their `.js` would be a useful feature that I'd be happy to help with! However, I wanted to get your input on the issue before I started down any red herring paths due to my lack of knowledge with your work here. 

In my case, `path` and `fs` are pretty standard and used in your extension - I'm thinking maybe there is a way to hand those modules references to loaded plugins? Or maybe I need to do some "bundling" on my plugin's end... 

Thanks for your time and hard work, let me know what you think!

**Comment by hediet** [comment]
Hi! Thanks for reaching out!

That is right, `require` is not supported in Draw.io plugins.
As the plugins are loaded in the webview, you will having a hard time adding support for `require`.
The draw.io website has the same limitation.

> there is a way to hand those modules references to loaded plugins?

Unfortunately, this is not possible. Draw.io plugins are run inside a webview that Draw.io is running in. The VS Code extension is a nodejs script that runs in the extension host process.
In case of codespaces, the webview and the extension host might not even be on the same computer.

> Or maybe I need to do some "bundling" on my plugin's end...

Yes. I can recommend to use webpack!

**Comment by hediet** [comment]
Btw. this extension already allows to link files natively, I guess this should address your use-case!

See #169.

**Comment by ZachsPage** [comment]
Great, thanks for your input! You are correct that Drawio website has this limitation, but I should of mentioned my Drawio plugin only supports / was tested in the local Electron version of Drawio - which allows the two `requires` that I have. Only supporting Electron allows for getting the current Drawio diagram's path, in turn allowing `relative paths` for file linkage portability.

This `require` issue was my first of surely many issues I will have for adding the VSCode environment support - like the way I am getting the current file's path with `fs` & the IPC call for opening the linked file in a new Drawio window. So just poking around for how to go about adding support - seems like its all on my end, and the `requires` will need bypassed. Getting the current Drawio file path from VSCode within the Drawio plugin may be interesting, if it is not totally "sandbox-ed" out...

I will be looking into webpack - thank you for the recommendation and your time responding back!

**Comment by hediet** [comment]
You really should have a look at #169!

> if it is not totally "sandbox-ed" out...

It is quite sandboxed...

VS Code Extensions can contribute Draw.io plugins, but there is currently no nice way to interact with them.

I'm open to extend [this](https://github.com/hediet/vscode-drawio/blob/master/src/DrawioExtensionApi.ts#L44) though.
Some Draw.io events could be forwarded to third party extensions.

**Comment by ZachsPage** [comment]
My small "issue" with https://github.com/hediet/vscode-drawio/issues/169 is it not being supported without the VSCode extension - not everyone uses VSCode on my team (against my suggestions). But it may be the trade off of "if you want to look at connected diagrams, get VSCode and this hediet's extension" :). I will look into it more, though, thank you!

Your second link should be useful... I will also look into that and make a PR if anything ever comes of it that isn't contrived only to support my use case, lol. Thanks for that!

**Comment by hediet** [comment]
> My small "issue" with #169 is it not being supported without the VSCode extension - not everyone uses VSCode on my team (against my suggestions). But it may be the trade off of "if you want to look at connected diagrams, get VSCode and this hediet's extension" :). I will look into it more, though, thank you!

I see. There is also #94. Maybe that could be used as basis so that it works on Draw.io VS Code and Draw.io desktop? I'm open to change the current Draw.io VS Code implementation of linked files.

**Comment by ZachsPage** [comment]
Lol, it does seem to be a common ask - Drawio itself does not support local `file://` links as mentioned in that "issue". I believe Drawio does this so that the user buys the Confluence extensions for linking diagrams :). So regardless there needs to be some "extension" for that feature - whether its a Drawio plugin, or your VSCode extension. 

From looking at the implementation [here](https://github.com/hediet/vscode-drawio/blob/master/src/features/CodeLinkFeature.ts) & [here](https://github.com/hediet/vscode-drawio/blob/master/drawio-custom-plugins/src/linkSelectedNodeWithData.ts), is that file link "absolute", or does it do relative linking somehow? Curious considering the portability between dev's workspaces... your method of embedding custom data in the Drawio cells is clean btw - doing `key value` seems better than encoding an object like mine lol.

**Comment by hediet** [comment]
> "absolute", or does it do relative linking somehow? 

It can be both, but only relative links written to the diagram when using the "link file to active node" feature.

> your method of embedding custom data in the Drawio cells is clean btw 

To encode deep objects as list of keys, I created [json-to-dictionary](https://github.com/hediet/json-to-dictionary/blob/master/test/jsonToDictionary.test.ts#L36).

**Comment by ZachsPage** [comment]
Okay, awesome. json-to-dictionary is great too, thanks for the link! I'll will just push other devs on the team to use this feature then. Thanks again for your time!
