### ISSUE TITLE
Rounded arrows do not get unrounded when deactivating Rounded option in page settings.

### ISSUE THREAD

**Issue by elrindir** [hediet/vscode-drawio#264]
## 1. Arrow lines and rectangles not rounded
![image](https://user-images.githubusercontent.com/79482581/133694783-4446ef57-aa86-4360-899e-1f141d07eb91.png)

## 2. Checkbox 'rounded' in page settings checked
![image](https://user-images.githubusercontent.com/79482581/133694892-40ac29a4-b764-4a8c-bb71-2980b0ca33d1.png)

## 3. Checkbox unchecked, lines are still rounded
![image](https://user-images.githubusercontent.com/79482581/133694920-a65244d4-f37c-4258-a5a9-8b33021044fc.png)

**Comment by hediet** [comment]
Does this problem also happen on https://app.diagrams.net/?

**Comment by elrindir** [comment]
> Does this problem also happen on https://app.diagrams.net/?

Yes the same behavior also occurs there too.
The style property of all lines gets changed to 'rounded'. To get back, you have to click on each line and select the 'sharp' style.

**Comment by hediet** [comment]
Then it is an issue of draw.io, not the vscode integration. Please file an issue in the draw.io repository.
