### ISSUE TITLE
Viewing diffs

### ISSUE THREAD

**Issue by timker** [hediet/vscode-drawio#27]
Currently viewing diff's doesn't seem to work
two "drawio widgets" show but, only the final image renders

There is also a lot of UI that renders, and there is not much space on the screen
![image](https://user-images.githubusercontent.com/659555/81764204-2082e800-9525-11ea-858d-824785a01b60.png)

Maybe just the image without the UI,
Or even just the xml?

Thanks for your work, It's awesome!

**Comment by hediet** [comment]
Hmm, interesting point. I don't think VS Code really provides an answer for that yet.

**Comment by timker** [comment]
Looks like the disabling UI can be viewed from looking at the resource uri,
https://github.com/microsoft/vscode/issues/97683#issuecomment-628186766

But for more complex merging there *might* be some thing in the future, as vscode is adding 3-way merge support:

However the vscode 2020 roadmap is adding 3-way support

> Provide full merge support (3-way)
https://github.com/microsoft/vscode/wiki/Roadmap#scm

so maybe the story will improve then?

**Comment by timker** [comment]
or perhaps on a diff for .drawio.svg and .drawio.png you would fall back to the default diff?

**Comment by hediet** [comment]
@timker I would like to fall back, but I don't think vscode allows me to do that. I'll see whether I can disable all ui elements.
________________________________

**Comment by hediet** [comment]
This is what it looks now for write conflicts:

![image](https://user-images.githubusercontent.com/2931520/83359036-d0ef4980-a377-11ea-98f7-e34f0e2a0147.png)

Due to https://github.com/microsoft/vscode/issues/97683, this is also as much as I can detect on my end.

**Comment by petervandivier** [comment]
> @timker I would like to fall back, but I don't think vscode allows me to do that. I'll see whether I can disable all ui elements.

I'm not quite certain from reading the linked articles, but is there in fact a User Setting one can toggle to coerce the diff to be read as text? 

e.g.

Text diff may be be preferable in some cases...
<img width="500" alt="Screenshot 2020-07-24 at 12 36 58" src="https://user-images.githubusercontent.com/10898767/88387463-61f80500-cdaa-11ea-9cde-f6c923a0611f.png">

... rather than image comparison
<img width="500" alt="Screenshot 2020-07-24 at 12 36 45" src="https://user-images.githubusercontent.com/10898767/88387467-645a5f00-cdaa-11ea-89b2-e493f5e3ce41.png">

**Comment by hediet** [comment]
I don't think VS Code allows that. Please open an issue there.

**Comment by petervandivier** [comment]
I started to but I can't think of a sensible way to request "_please disable an extension for files launched from the source control pane_". I may do later and will link back if so; but in the meantime, please find below [a reasonably quick in-place workaround to coerce this behaviour][1]

1. Open diff in "Source Control"
2. Tab to "Extentions" (macos hotkey `⬆ ⌘ X`)
3. Search for the extension "extension id `hediet.vscode-drawio`"
4. Click "Disable (workspace)" (can't find a hotkey path for this atm)
5. Click "`Reload Required`"
6. Reopen as in Step 1

![ezgif-4-c4ef2e51ba25](https://user-images.githubusercontent.com/10898767/88389841-2f044000-cdaf-11ea-8394-c912474b6ef2.gif)

To re-enable the extension, it appears a command-shift-P (`⬆ ⌘ P`) is reasonably quick.

[1]: https://i.imgur.com/7qYKzou.mp4

**Comment by hediet** [comment]
You don't need to disable the entire extension for that - you can also just open the drawio file with the text editor (I think right click + open in...).
However, you currently cannot specify a editor for diffs - it will always use the same editor configured for viewing non-diffs.

**Comment by petervandivier** [comment]
Yea - the diff editor is the one I was trying to get at. 

Thanks for the "right-click + `Open With...`" protip though! I'd been keeping an instance of Sublime Text handy to view files as text.

**Comment by benlindsay** [comment]
I have this issue too, I can open the text for editing by right-clicking the file and choosing "Open With", then "Text Editor". I just wish I could do the same thing in the Source Control panel...I really see no reason why VSCode shouldn't allow choosing between the built-in text editor diff and the custom diff tool. Any idea where to request a change like that?
