### ISSUE TITLE
Question about intended use case of `Draw.io Integration - Insiders Build`

### ISSUE THREAD

**Issue by Krebrov001** [hediet/vscode-drawio#272]
I see that there are two very similar extensions
 - `Draw.io Integration`
 - `Draw.io Integration - Insiders Build`

I am using Insiders Version of Visual Studio Code IDE. Which extension should I use? Do I have to use the `Draw.io Integration - Insiders Build`? Is `Draw.io Integration - Insiders Build` intended to be used with Insiders Version of Visual Studio Code IDE?

**Comment by hediet** [comment]
Please see the readme of the extensions.

It does not matter if you use stable or insiders of VS Code.

**Comment by Krebrov001** [comment]
@hediet 
> Please see the readme of the extensions.
> 
> It does not matter if you use stable or insiders of VS Code.

That you for responding so quickly. If I understand correctly, the Insiders Build of the extension itself is completely unrelated different thing than Insiders of VS Code? There is no implication of mutual dependency? So I can use `Draw.io Integration` with Insiders Version of Visual Studio Code IDE, and vice versa? Please confirm.

**Comment by hediet** [comment]
Yes
