### ISSUE TITLE
issue about code link to a function(c/c++)

### ISSUE THREAD

**Issue by wpz1988** [hediet/vscode-drawio#289]
Currently I can success jump to the definition of a symbol ,
But it cannot jump to an definition of a function,  for the description of  code-link feature -> [LINK](https://github.com/hediet/vscode-drawio/blob/master/docs/code-link.md) 
"In TypeScript, symbols are functions, classes, consts, interfaces, ..."

I am not sure about what this really means, is it only for TypeScript to jump to an symbols are functions?
or how can it jump to an definition of a function?
![image](https://user-images.githubusercontent.com/4659680/148174658-e1da561c-8042-4b6f-9444-99c1914bf36d.png)

**Comment by hediet** [comment]
Can you press F1, press backspace and type `#SetWorkSheet` and hit enter?
Does that work? If not, this feature won't work neither.

**Comment by wpz1988** [comment]
> Can you press F1, press backspace and type `#SetWorkSheet` and hit enter? Does that work? If not, this feature won't work neither.
do you mean type as below?
![image](https://user-images.githubusercontent.com/4659680/148306420-1de22424-eb8b-4e9f-8f5b-2164db0daa4a.png)
![image](https://user-images.githubusercontent.com/4659680/148306506-f09f9956-6ba3-4cad-b40e-694ad7aef72c.png)

**Comment by wpz1988** [comment]
> Can you press F1, press backspace and type `#SetWorkSheet` and hit enter? Does that work? If not, this feature won't work neither.

![image](https://user-images.githubusercontent.com/4659680/148306420-1de22424-eb8b-4e9f-8f5b-2164db0daa4a.png)
![image](https://user-images.githubusercontent.com/4659680/148306566-731aca18-f339-4fc0-b23d-4df1d4244ff5.png)

**Comment by hediet** [comment]
Yes, `#alarm18sec` should work as node label then.

**Comment by wpz1988** [comment]
> Yes, `#alarm18sec` should work as node label then.

so, can it be fixed?

**Comment by hediet** [comment]
It should work already ;)

**Comment by wpz1988** [comment]
> It should work already ;)
![image](https://user-images.githubusercontent.com/4659680/148405465-3ef0a516-d82d-4290-96db-64081b08e10a.png)
in this screenshot ,I double click the #alarm18Sec label, the vscode will should the  comment" No symbol found with name..."

and I try another simply example, the result is same.
![image](https://user-images.githubusercontent.com/4659680/148406099-65bb7301-73b6-4433-8912-a5c806b4e007.png)

So maybe there is another way to name the label?
