### ISSUE TITLE
Colors + Dark Theme

### ISSUE THREAD

**Issue by kolarski** [hediet/vscode-drawio#29]
I have a color issue when using the dark mode of draw.io.

The current default behavior is great, for example:
A line looks white in VS Code, when I export in png for example the line is black on white background. 

But if you happen to change the line color to white or black manually, I couldn't go back to that behavior. 

1) Either the the line is black and not visible in VS Code, but exports fine
or 
2) The line is white and visible in VS Code, but exports white on white background. 

So I guess my question is: Is there a way to get back to the default behavior, once you mess with the colors.

**Comment by hediet** [comment]
Actually, I don't know. You could compare the xml to see what the difference is. It would be awesome if you could share your findings!

As I don't can fix anything in my extension to help you there, I'm going to close this issue.
