### ISSUE TITLE
Allow to set custom Draw.io configuration from vscode (for custom fonts)

### ISSUE THREAD

**Issue by mplattner** [hediet/vscode-drawio#30]
Draw.io desktop allows to set a configuration via `Extras -> Configuration...`
I use it to set custom fonts that I use regularly, e.g. CMU Serif to match figures with LaTeX documents:

```
{
  "compressXml": false,
  "customFonts": [
    "CMU Serif",
    "CMU Typewriter Text"
  ]
}
```

I see that you set the `compressXml` option in https://github.com/hediet/vscode-drawio/blob/master/src/DrawioInstance.ts#L86.
Maybe an option can be added to the vscode extension to also set `customFonts` to a user-defined list.

Thanks for this great extension! :+1:

**Comment by rhofer** [comment]
Actually this is related to #17 , and according to [how to configure draw.io](https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-) there even are a lot of configuration options available. (apparently to set correctly `defaultCustomLibraries` would solve #17 )

I just wonder, whether configuration could be externalized, in general. Similar as you may have stuff in a folder as `.vscode` (e.g. in `settings.json`) or specifically files in the main folder as `.eslintrc`, `.gitignore`, etc.

Could there be something similar as e.g. `.vscode-drawio` what comprises the extension's configuration and which is loaded whenever the extension is used? (Or it may belongs in the `.vscode` subfolder ... sorry for being to general. I'm not familiar with this in details.)

**Comment by mplattner** [comment]
Yeah, having a dedicated file is a good idea as well. Maybe easier to implement as adding vscode-extension settings for every option that draw.io provides.

**Comment by hediet** [comment]
I'm not so sure whether a dedicated file is such a good idea. I think `settings.json` is just for stuff like this - it features workspace overrides and synchronization. I have to think about this.

Also I need to figure out which of these configurable options can be changed in draw.io. These need to be written back.

**Comment by mplattner** [comment]
I agree, for a handful of options the vscode-settings are best, I think.
However, if draw.io supports dozens of options, or if the settings can contain complex objects (like nested arrays), a separate file might be easier.
(I'm was just brainstorming as someone who's not familiar with vscode extension development - so I'm probably not a big help here and will stop :))
Thanks again! :+1:

**Comment by hediet** [comment]
Fixed in v0.4.0.

**Comment by mplattner** [comment]
Nice, thank you so much!

For other users: it seems like a `.drawio-config` dict is needed within `hediet.vscode-drawio.local-storage`, e.g within `settings.json` I have:

```json
{
    "hediet.vscode-drawio.local-storage": {
        ".drawio-config": {
            "customFonts": [
                "CMU Serif",
                "CMU Typewriter Text"
            ]
        }
    }
}
```

**Comment by hediet** [comment]
>  (Btw, I think it's local-storage, not localSettings, right?)

Yes ;) Please bear in mind that I don't support changing the local storage manually!
Invalid values there might crash the app. Also, I might overwrite some of these options in future updates.

**Comment by lucianmoldovanu** [comment]
Hi @hediet . Is setting a local configuration still supported, or is it covered by a different feature? I need to set a default style (connector type), I try to do so based on @mplattner's comment above (in settings.json) yet whenever I open a .drawio file the settings get overwritten (and thus never applied).
