### ISSUE TITLE
Opening a `.drawio` file created by the official app invert the text and background color

### ISSUE THREAD

**Issue by AFCMS** [hediet/vscode-drawio#300]
In the app:

![image](https://user-images.githubusercontent.com/61794590/155767109-9f919d90-9231-4863-b763-8734901ebe78.png)

Opening the file in vscode:
![image](https://user-images.githubusercontent.com/61794590/155767205-c5be8bfa-967e-401e-8746-983812ff51c1.png)

**Comment by hediet** [comment]
You can change the theme to "light" in the statusbar.
