### ISSUE TITLE
Support advanced export options

### ISSUE THREAD

**Issue by yetiansh** [hediet/vscode-drawio#314]
Hi, could you support more advanced export options? Some users and I may need to export PNGs with a custom dpi, e.g., 400, while this is not supported. Please remind me if this feature is already available. Thanks for your work :)

**Comment by hediet** [comment]
![image](https://user-images.githubusercontent.com/2931520/163968985-772477b1-4bd3-4512-b500-17b695b06360.png)

Here you can set a zoom level (e.g. 400%):
![image](https://user-images.githubusercontent.com/2931520/163969015-6abec68b-a599-4c1b-85ac-d6b04f36b832.png)
