### ISSUE TITLE
automatic export

### ISSUE THREAD

**Issue by onlygecko** [hediet/vscode-drawio#325]
Hi,

is there way to automatically export the diagram (to PNG, ...) when the diagram has been changed (and saved)?

Greetings,
Peter

**Comment by hediet** [comment]
No. Shouldn't be impossible to implement though.

What should the feature be?

**Comment by onlygecko** [comment]
First of all thanks for the quick response. :-)

Scenario: I'm editing a diagram which I want to use in my markdown / Word / ... document. But as human being I am lazy, so it would be great if a png (or svg) version would be automatically generated with the same filename (but other suffix), when the original drawio diagram has been saved.

Maybe the vs code extension settings could be used to determine if diagrams should exported automatically and which type should be used.

What do You think - Is this a valid use case?

**Comment by hediet** [comment]
Did you know you can just rename your diagram to `myDiagram.dio.svg`? or `myDiagram.dio.png`?
After you edit & save this file in VS Code, that file becomes both a diagram and image.
I recommend SVG though.

**Comment by onlygecko** [comment]
He, this is an amazing tip! :star_struck: I did not know that and this even better. And I don't want to know what kind of magic is happening there - I just love it. :smiley:
