### ISSUE TITLE
Change extension language standalone

### ISSUE THREAD

**Issue by qrqhuang** [hediet/vscode-drawio#330]
I use english as my default vs language.
But this extension I want to show Chinese instead.
Can this be configured and standalone with ide ?

**Comment by esailes** [comment]
this extension use the `env.language`

but

`.vscode\extensions\hediet.vscode-drawio-insiders-build-1.6.502\drawio\src\main\webapp\resources`
replace  `dia.txt` to   `dia_zh.txt`

**Comment by qrqhuang** [comment]
@esailes It works. Thanks.
