### ISSUE TITLE
Create drawio image inplace in Markdown

### ISSUE THREAD

**Issue by gribok** [hediet/vscode-drawio#332]
Thanks for this great feature! It helps me in my daily business.

Do you know, how to create a drawio file in a Markdown file inplace?
My current workflow is as follows:
1. Create drawio file in VSCode explorer
2. Add drawio file in Markdown via `![](<IMAGE>)`
3. `CMD+CLICK` on image path to open drawio

It would be great to remove step 1 and step 2.
And to create new drawio image by click on step 3.

Any ideas?

**Comment by hediet** [comment]
I think there used to be a feature request for VS Code to enable creating files when clicking uris to files that don't exist yet.

Any ideas how it should work?

**Comment by davea38** [comment]
Surely you just right click in file explorer and select new file, then name it *.drawio? Seems just as quick...

**Comment by hediet** [comment]
Closing, as this is a vscode feature request. Nothing I can do here.
