### ISSUE TITLE
Make page in drawio project selectable in markdown

### ISSUE THREAD

**Issue by olischloesser** [hediet/vscode-drawio#333]
When inserting the drawio only the current page is shown. If the file has multiple pages there is no way to select that when the picture is imported.

Context:
To avoid having a lot of files containing pictures in the documentation, I put similar things in one file with different pages.

**Comment by richelin** [comment]
I just ran into that issue myself today, although I did not have any luck making the `.drawio.svg` appear in markdown. I'm not sure if the fact I started with `.drawio` then renamed it to `.drawio.svg` is what caused my image not to appear in my documentation. (markdown and sphinx).

I fixed it in my sphinx documentation by installing the [sphinxcontrib-drawio extension](https://github.com/Modelmat/sphinxcontrib-drawio). This extension allow you to select the page to display. Hope that helps.

**Comment by hediet** [comment]
Unfortunately, this is not possible.
