### ISSUE TITLE
Can't preview *.drawio in Markdown.

### ISSUE THREAD

**Issue by GitHubWesley** [hediet/vscode-drawio#341]
Hi,

Thanks for the awsome extension!

I can't preview drawio diagram in Markdown preview, not sure whether it is a bug.

![image](https://user-images.githubusercontent.com/35339348/195006937-60869f71-b0ef-467d-9310-814bfc55fed5.png)

**Comment by Regenhardt** [comment]
Markdown knows everything html knows, so to display an image it has to b jpg/png/svg and maybe some other image format, but .drawio isn't actually an image format. 

You can however create a test.drawio.png file, and drawio will let you edit it and immediately add working png code, while markdown will display the png image.

**Comment by davea38** [comment]
Yeah I have been saving files as *.drawio.png and they work as Markdown images :) Svg was the first format I tried but that didn't work (presumably no EXIF info?)

**Comment by Regenhardt** [comment]
Not sure why svg doesn't work for you, I can use it the same as png:
![image](https://user-images.githubusercontent.com/10476293/202702854-34e9f8b2-274e-4446-a7d1-14a5009ec8dd.png)

**Comment by GitHubWesley** [comment]
> Markdown knows everything html knows, so to display an image it has to b jpg/png/svg and maybe some other image format, but .drawio isn't actually an image format.
> 
> You can however create a test.drawio.png file, and drawio will let you edit it and immediately add working png code, while markdown will display the png image.

OK thanks, seems like I have to create a new png file from my .drawio file...

**Comment by hediet** [comment]
> create a new png file from my .drawio file...

You should be able to just rename it. Open the file and save it and then it should be a proper png files.

Just try to use SVG whenever possible.
