### ISSUE TITLE
Ability to define the png output size multiplier.

### ISSUE THREAD

**Issue by AssassinLV** [hediet/vscode-drawio#344]
When making your diagram you might sometimes want to have output 2x or 4x of the resolution then actual working resolution, especially considering 4k laptops, as on those you have to zoom in to 400% to even be able to read anything. So, it would be great option to actually define resolution multiplier (or percentage). It could be added also as a setting.

**Comment by AssassinLV** [comment]
Currently for me workaround is to make a screenshot from the editor on 4k laptop screen rather than using actual export file...

**Comment by hediet** [comment]
You can set a zoom level in properties.
