### ISSUE TITLE
Code link not working?

### ISSUE THREAD

**Issue by chipbite** [hediet/vscode-drawio#349]
Hi! 
I am trying to get the code links feature to work, I cannot get it to react at all, it seems.. 
Code link in status bar is "filled in".

See this small recording:
![drawio-vscode-code-links](https://user-images.githubusercontent.com/559199/202665683-13bce43d-a2a3-4039-8bf3-9efecbd54baf.gif)

What could I be doing wrong? 
Ctrl-T to jump to symbols work, so it seems that the symbols are there in vs code...

Is there some config I can check? Or log? 

Thanks for a very nice plugin!
BR! /marcus

**Comment by mihaiconstantin** [comment]
I am exercising the same. @chipbite, have you found a solution, or what is causing this?

**Comment by chipbite** [comment]
Thanks @mihaiconstantin, I will do try this and report back!

**Comment by hediet** [comment]
There is a code link button in the status bar to enable code links. By default they are disabled, as a double click is usually used to edit a node.
