### ISSUE TITLE
Export single/multiple from file explorer or command palette

### ISSUE THREAD

**Issue by FreHu** [hediet/vscode-drawio#35]
Using vscode I can easily manage documentation with multiple diagrams versioned in git. This is an amazing improvement for me. I'm missing some quality of life features though.

Currently you have to do Export->Download->Pick target folder for each diagram.

I'm proposing some quicker options:

1.  An export option when rightclicking a .drawio file.
2.  Export all diagrams in current folder.

These exports would use the last specified export settings to avoid any dialogs.

**Comment by hediet** [comment]
Hi, thanks for your feedback!
Can you describe why the *.drawio.svg or the upcoming *.drawio.png feature does not work for you?

**Comment by FreHu** [comment]
Now that I'm looking at it thoroughly, I can accomplish everything I need using drawio.svg. Is the functionality completely equivalent? Perhaps there is still some use for the mass export as it has more settings - for example export all to PDF or with a higher DPI.

**Comment by hediet** [comment]
> functionality completely equivalent

Yes. Its exactly as if you would export it as svg (with an embedded drawio diagram - so if you share the svg, people can extract/edit the diagram).

I don't like (manual) exports and think there are usually better ways to achieve the same result.

Also, I don't think I can support some kind of mass export within a reasonable amount of time. I think a CLI would be great for that, but that is something completely out of scope for this extension.

**Comment by FreHu** [comment]
Yeah, a CLI would be a better option. Just keep up what you're doing already, it seems like you have the right ideas :).
