### ISSUE TITLE
Configuration to disable use of ForeignObject

### ISSUE THREAD

**Issue by bruno-villa** [hediet/vscode-drawio#353]
As detailed in the [draw.io blog](https://www.diagrams.net/doc/faq/svg-export-text-problems) it should be possible to add a config parameter `"simpleLabels": true` in order to avoid the usage of ForeignObjects, which can be useful for diagrams not intended for web use.

Is there a way to configure this setting for the VS Code extension? I did not find a straightforward way by editing `settings.json`. Also tried using 
```
"hediet.vscode-drawio.online-url": "https://embed.diagrams.net/#_CONFIG_UzV3UjUyyk0tSk8F0qrGjqpggeLM3IKcVJ/EpNScYoh4SVFpqqq5CxABAA=="
```
but that did not have any effect.

**Comment by hediet** [comment]
I'm open for a PR here!

**Comment by bruno-villa** [comment]
Alright looked a bit more in the docs and it is clear it is simply an URL parameter that needs to be passed when the custom editor is created. I've opened #355 for this.

**Comment by hediet** [comment]
Implemented in https://github.com/hediet/vscode-drawio/pull/355
