### ISSUE TITLE
Shapes not loading (BPMN + general)

### ISSUE THREAD

**Issue by philip-denys** [hediet/vscode-drawio#354]
When choosing the BPMN2.0 shapes (clicking on it) it doesn't show the shapes 

These are the ones I've added next to the standard shapes:
BPMN2.0 - general
BPMN2.0 - tasks
BPMN2.0 - choreographies
BPMN2.0 - Events
BPMN2.0 - Gateways
Sometimes I get lucky that it does load the shapes and at moments none of the shapes load (like general)

tried uninstalling and installing the vs extension, but no changes...

my specs:
MacBook pro
<img width="392" alt="Screenshot 2022-12-05 at 13 11 18" src="https://user-images.githubusercontent.com/61691643/205634275-f48a595b-d2d9-47e4-bdb4-a77ec4c9b19c.png">

**Comment by DanielTheCoder** [comment]
I think it's the same problem as described here https://github.com/hediet/vscode-drawio/issues/294 and https://github.com/hediet/vscode-drawio/issues/238 and https://github.com/hediet/vscode-drawio/issues/354
