### ISSUE TITLE
Can't open a blank ".dio" or ".drawio" file

### ISSUE THREAD

**Issue by perettigiuliano** [hediet/vscode-drawio#356]
Opening a new (empty) ".dio" or ".drawio" file It shows:
![image](https://user-images.githubusercontent.com/148322/207543899-df6a60a9-65cd-49ac-adfe-3c4930ce346f.png)
![image](https://user-images.githubusercontent.com/148322/207543945-2a3eed14-2242-4b6a-801e-8fbf4d89e0ac.png)

The first one says: it is not a diagram file.

I have just installed the extension:
![image](https://user-images.githubusercontent.com/148322/207544398-a957c44e-2fca-4528-bb93-4ca45a197962.png)
and for VC Code I have:
![image](https://user-images.githubusercontent.com/148322/207544266-e6625041-9f99-49ea-8efa-6e3e4b071195.png)

**Comment by perettigiuliano** [comment]
What do you mean with "default settings"?
I have just created a new and empty ".dio" file

**Comment by happyTonakai** [comment]
Please disable all the other extensions and try again.

**Comment by perettigiuliano** [comment]
I have just tried what suggested, here a screenshot of VSCode with only 2 extensions enabled:
![image](https://user-images.githubusercontent.com/148322/207790560-83fb32de-82ab-4ebd-b858-6f309f0bc0d5.png)
But the result is the same

**Comment by perettigiuliano** [comment]
Any other suggestion?
