### ISSUE TITLE
No menu for undoing image resize preference

### ISSUE THREAD

**Issue by jgscherber** [hediet/vscode-drawio#360]
After checking the box on the below dialog, there's no way to undo whichever setting is remembered. I've tried removing and reinstalling the extension and setting is still remembered.

![image](https://user-images.githubusercontent.com/6207661/210872041-03899ad4-5f29-4acf-b1f2-51ecad4281c7.png)

**Comment by hediet** [comment]
There is now a vscode native setting to control this behavior. If this setting is not configured, drawio will prompt.
