### ISSUE TITLE
Missing fill style

### ISSUE THREAD

**Issue by ondrejtomcik** [hediet/vscode-drawio#361]
Hi Henning!

The feature which is available on the draw.io is not available in your vscode plugin, despite the information from README.md - `This extension bundles a recent version of Draw.io.`. 

I am searching for the `fillStyle=cross-hatch;`, in combination with `sketch=0;`:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/6858585/211109252-d1151f00-e736-4289-aac2-2117edc3875b.png">

Any plans to include it?

https://github.com/jgraph/drawio/issues/753#issuecomment-1184208519

Thanks
Ondrej

**Comment by hediet** [comment]
Fixed in #362
