### ISSUE TITLE
Remote Development: drawio files not opening

### ISSUE THREAD

**Issue by derekwallace** [hediet/vscode-drawio#37]
HI,
I use remote devlopment to ssh connect to linux box. install the extension and it installed on remote machine. when i create a .drawio file i have the open with option to use drawio. however the drawio editor does not open.
![image](https://user-images.githubusercontent.com/5574230/82124830-8c6d8680-9799-11ea-823c-d2e69bc8d094.png)

![image](https://user-images.githubusercontent.com/5574230/82124832-95f6ee80-9799-11ea-9b3f-d07f88e2416d.png)

![image](https://user-images.githubusercontent.com/5574230/82124838-a27b4700-9799-11ea-8472-19f2c9f67602.png)

if i use a normal workspace and install drawio extension it works as expected.

is this a known issue or what can i do to debug .

Thx
derek

**Comment by hediet** [comment]
Hey, which version of this extension do you use?

**Comment by hediet** [comment]
Thanks for your screenshots! This bug is already covered in #8. I think I might be able to fix this today.

**Comment by derekwallace** [comment]
version 0.3.0

**Comment by hediet** [comment]
Sorry, your screenshot already shows the version! I fixed this bug in another extension of me, I confused myself :D
