### ISSUE TITLE
How to enable spell checking when editing diagrams in VSCode?

### ISSUE THREAD

**Issue by dpar39** [hediet/vscode-drawio#374]
Is there a way to enable some support for spell checking when editing drawio diagrams in VSCode?

**Comment by hediet** [comment]
Not that I know of unfortunately.

**Comment by ZacZhangzhuo** [comment]
> Not that I know of unfortunately.

Thanks for the reply! But is there also a way to spell-check the XML file? as we know the .drawio file can also be opened as .XML.

**Comment by hediet** [comment]
> But is there also a way to spell-check the XML file

Maybe there is some extension! This is out of scope for this extension though.
