### ISSUE TITLE
Does it support line crossing?

### ISSUE THREAD

**Issue by HeartAndSoul001** [hediet/vscode-drawio#377]
Hi, I am someone who enjoys using Drawio you make, and thanks a lot. When I draw a Network topology diagram, which include switches, routers，I want to make some crossing connecting lines. I wonder if Drawio support the highlighting of intersections?

**Comment by hediet** [comment]
This extension only integrates draw.io into VS Code. Please create a feature request directly for draw.io. Thanks! :)
