### ISSUE TITLE
How to open .svg and .png files in the extension please?

### ISSUE THREAD

**Issue by hawkinsji** [hediet/vscode-drawio#381]
Hi, Is there a way to force VSCode (or VSCodium) to open a Drawio SVG file in the plugin if the filename doesn't have the .drawio.svg suffix please?

**Comment by hediet** [comment]
![chrome_DclLMtZDCY](https://user-images.githubusercontent.com/2931520/230036758-c0599eca-7427-4b5f-9d74-27d56d05e8c1.png)

**Comment by hawkinsji** [comment]
Hi @hediet , Thank you for posting this. I tried it and it didn't quite work. It seems that I also had to add workbench editor associations, like this.

    "files.associations": {
        "*.svg": "drawio",
        "*.png": "drawio"
    },
    "workbench.editorAssociations": {
        "*.png": "hediet.vscode-drawio",
        "*.svg": "hediet.vscode-drawio-text"
    }

I discovered the workbench associations piece from trying the Open With option on files with the different extensions, .drawio.svg .svg and so on.
Cheers, Jim
