### ISSUE TITLE
Add Export Option

### ISSUE THREAD

**Issue by joey66666** [hediet/vscode-drawio#39]
Adding support to export png/jpg would be great.

**Comment by hediet** [comment]
Urgh I just removed it because it (pdf export) did not work. I don't have the manpower to fix that soon.

Soon you will be able to edit png natively, so you don't even need to export!

**Comment by joey66666** [comment]
> Urgh I just removed it because it (pdf export) did not work. I don't have the manpower to fix that soon.
> 
> Soon you will be able to edit png natively, so you don't even need to export!

OK, thanks for your reply.
I have to use [draw.io](https://app.diagrams.net/) currently because I have to export png and insert into my paper.

**Comment by hediet** [comment]
You should use SVG for LaTeX anyways! It's a much better quality and text gets rendered by LaTeX.

**Comment by joey66666** [comment]
> You should use SVG for LaTeX anyways! It's a much better quality and text gets rendered by LaTeX.

But my school requires Microsoft Word format, sad. 😞

**Comment by hediet** [comment]
Can't you embed svgs in word?

**Comment by 1751200** [comment]
> You should use SVG for LaTeX anyways! It's a much better quality and text gets rendered by LaTeX.

Actually it is not convenient to include SVG diagrams in LaTeX (the svg package is needed and shell escape shall be enabled when using the command \includesvg{}). Anyway it is easy to convert svgs to other formats and thanks for your devotion.

**Comment by hediet** [comment]
>  shell escape

Can you tell me more about that? I hope you cannot inject shell scripts in SVGs when using \includesvg?

**Comment by 1751200** [comment]
> Can you tell me more about that?

The `svg` package relies on `Inkscape` as a backend to convert the svg drawing into a pdf file. So it is required to use `--shell-escape` to load additional programs. 

https://tex.stackexchange.com/questions/2099/how-to-include-svg-diagrams-in-latex

**Comment by SaifAqqad** [comment]
> But my school requires Microsoft Word format, sad. 😞

You can use this [office add-in](https://store.office.com/addinsinstallpage.aspx?rs=en-001&assetid=WA200000113) to insert draw.io diagrams into office documents

**Comment by hediet** [comment]
Would you be happy with a solution that exports the svg to pdf/png/jpeg/whatever, @joey66666?

**Comment by joey66666** [comment]
> Would you be happy with a solution that exports the svg to pdf/png/jpeg/whatever, @joey66666?

Do you mean import svg then export to pdf/png/whatever?

**Comment by hediet** [comment]
Like a third party extension that provides a context menu for arbitrary svg files. This context menu would contain "Export To Png" and "Export To Pdf".

**Comment by joey66666** [comment]
> Like a third party extension that provides a context menu for arbitrary svg files. This context menu would contain "Export To Png" and "Export To Pdf".

I am not clear about the procedure, can I export .png directly from .drawio file with the extension?

**Comment by supachris28** [comment]
Export to PNG was working for me. The filename wasn't right, but it went into my Downloads folder (on Windows) and I could push the pictures wherever I wanted. Now I have diagrams in VS Code that I have to upload to draw.io just to get a PNG.

**Comment by hediet** [comment]
Soon (like in two to three weeks) you probably will be able to edit *.drawio.png files directly!

**Comment by MagicLegend** [comment]
> You should use SVG for LaTeX anyways! It's a much better quality and text gets rendered by LaTeX.

And how would you propose to do this? The `svg` package doesn't appear to like the double `.drawio.svg` file extension that this extension requires for direct editing. I just get an `Package svg Error: File 'network.svg' is missing.` with an `\includesvg{figures/network.drawio.svg}` command. The upcoming `.drawio.png` would of course fix this, but as you said; `svg` is way sharper and more scalable. I figured this is an issue with `svg`; but since you mention it here too I'm wondering if something else is up...

**Comment by hediet** [comment]
> The svg package doesn't appear to like the double .drawio.svg file extension that this extension requires for direct editing.

Why does it make this assumption? Anyways, you can rename your *.drawio.svg to just *.svg and configure vscode to use the drawio editor for arbitrary svg files (see readme).

**Comment by hediet** [comment]
Would you be happy if I publish another extension that adds an "Export to {png, pdf, jpeg, ...}" context menu for *.svg files? It would work for arbitrary svg files.
That would be simpler and more general than trying to fix drawio's export dialogs that will never integrate very well with vs code.

**Comment by MagicLegend** [comment]
> > The svg package doesn't appear to like the double .drawio.svg file extension that this extension requires for direct editing.
> 
> Why does it make this assumption? Anyways, you can rename your *.drawio.svg to just *.svg and configure vscode to use the drawio editor for arbitrary svg files (see readme).

No clue. I figured out that it behaves differently from the normal `\includegraphics` in that it also requires `./` in it's path. And you are correct in the extra setting, I literally saw that option as I was reading through the documentation (RTFM eh?), and that (combined with the `./` thing) fixes my issues (sorta). I ended up with: `\includesvg{./figures/network.svg}`.

**Comment by joey66666** [comment]
> Like a third party extension that provides a context menu for arbitrary svg files. This context menu would contain "Export To Png" and "Export To Pdf".

If need many work would it be a burden for you? 
I could use draw.io currently, so it might not be necessary to add this to VS Code. 
Whatever, Thank you for your reply and patience.👍🏻

**Comment by vpedrosa** [comment]
Hello! 
@hediet "Export to PNG" is a basic feature and normal users would approve to copy&paste in Word and then Export to PDF there.
Is impossible to keep only "Export to PNG" feature if still works?

**Comment by hediet** [comment]
Do you think this export to png feature is relevant anymore when the drawio.png editor is available?

If so, how do I teach users that they don't need to export to png everytime, but can just directly edit the png file with this drawio extension?

**Comment by vpedrosa** [comment]
I think it would be necessary as long as they have edited and saved in .drawio extension before.
There would be a bunch of users like me that have 20-40 diagrams in .drawio extension that would be great to keep editing and exporting.

For the user learning that you are referring to, I think making harder to save the files in .drawio extension would solve the problem (ie. default PNG on File > Save), and it's always good to have the feature to save and read in XML format (automatic scrapers, parsing, APIs, etc) that can be exported by some reason in PNG.

**Comment by hediet** [comment]
I splitted this issue into
* [Support PDF Export / Direct Edit](https://github.com/hediet/vscode-drawio/issues/55) and
* [Support PNG Export](https://github.com/hediet/vscode-drawio/issues/56)

Feel free to open a new issue for different formats, though I won't support JPEG directly (PNG is just superior in case of diagrams).
