### ISSUE TITLE
Configure whether to store drawio config in global or workspace settings

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#40]
Also, if the extension reads localStorage from workspace settings, the extension should not simply write localStorage back to the global config. It should either delete the workspace setting or write back to the workspace setting.

**Comment by rhofer** [comment]
I'm not sure whether I understood correctly.
However, my thinking is as following:
- The global config is fine to have my user settings, which are of general nature
- If the current workspace has a local setting it shall win over the global settings, means
  - For those json objects provided by global settings, where local workspace settings are undefined: the global settings apply
  - For those json objects provided by the local workspace settings, they shall win over the global settings : either replace (if already existant in global settings) or enhance (if not yet existant in global settings).
- Local workspace settings shall not automtaically propagate to global settings.

I think, if the behavor would be like this in general, we could achieve the demand to have a workspace where specific docu guidelines / visual styling is required for e.g. corporate identity or common architecture styles.

Does this match your thoughts?

**Comment by hediet** [comment]
> Does this match your thoughts?

Yes ;)

**Comment by hediet** [comment]
This is what the insiders does now:
* Workspace/Workspace Folder settings always have precedence.
* Only local storage settings are written back. They are written back to where they were read from.
* local storage is encoded. Users should not modify this setting manually.
* Instead, they should use `hediet.vscode-drawio.{*}` settings to configure what they want (they also can be configured on workspace or user level).
As of now, {*} can be:
* customFonts
* customLibraries

Please open individual issues for each additional property you would like to configure.
