### ISSUE TITLE
File>Save As SVG doesn't work as expected

### ISSUE THREAD

**Issue by thomastay** [hediet/vscode-drawio#41]
Maybe I'm interpreting this wrongly, but suppose I create a `file.drawio` file. I draw my diagram. Then I do (through VSCode) a File>Save As: `file.drawio.svg`

The svg file created isn't the one that can be directly embedded in Github. I had to go to Embed > SVG > Options (Fit), and then save that into the SVG file.

The svg file created through File>Save as looks like this:
```
<mxfile host="localhost" modified="2020-05-18T13:42:57.122Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.45.0 Chrome/78.0.3904.130 Electron/7.2.4 Safari/537.36" etag="w0Ix3sGhsgqnVdeELjn6" version="13.0.9">
    <diagram id="6hGFLwfOUW9BJ-s0fimq" name="Page-1">
        <mxGraphModel dx="675" dy="404" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
......
```

Which is the encoding that drawio uses, not the svg encoding. Am I missing something?

OS: Windows 10
VSCode version: 1.45.1
App extension: 0.4.0

EDIT: I had originally typed it as `file.draw.io.svg`

**Comment by hediet** [comment]
You need to save it as `file.drawio.svg`! (note the missing dot)

**Comment by hediet** [comment]
Oh, I see. This only works in the binary editor. Just rename your file to `foo.drawio.svg`, open it, change it and save it.

**Comment by thomastay** [comment]
oops, that extra dot is a typo. It is still not working. I have to go now, but i will upload some screenshots later.

**Comment by nothingismagick** [comment]
Yeah - this is what I am seeing too - the XML of a .drawio is obviously not an SVG, and there isn't a `File>Save As` button anymore... (I updated just now)

**Comment by hediet** [comment]
There is now `Draw.io: Convert To...` in the Insiders Build that lets you properly convert from `*.drawio` to `*.drawio.svg` file or vice versa.
Please open a new issue if this does not work.
