### ISSUE TITLE
Get rid of the iframe that hosts drawio

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#42]
# Problem
[Currently, an iframe is used to host drawio](https://github.com/hediet/vscode-drawio/blob/master/src/DrawioAppServer/HostedDrawioAppServer.ts#L62).

This prevents VS Code shortcuts from working (like ctrl+tab). Since some shortcuts might collide with drawio, this is actually a good thing with the current architecture.

However, copy and paste does not seem to work on mac due to this (#28).

# Solution
Host drawio without the top IFrame.
This can be done by using `webview.asWebUri(...)` or, maybe even better, by loading an html page that redirects to `http://localhost:${port}/index.html?...`.
In both cases, window.parent.postMessage must be patched to use the vscode api or something else like websockets (I'm not so sure whether the VSCode Webview API exists anymore after an redirect).

This would break the online version though.

Also, all shortcuts in drawio may have to be disabled. For every action, a proper VS Code command should be added with a default shortcut that the action in drawio had.
I think you can use `ui.actions...` to invoke actions inside plugins.

**Comment by Speedy37** [comment]
You can't redirect the top iframe, it violate some security settings.
At least it doesn't work in the inspector.

**Comment by Speedy37** [comment]
Nice idea about isolating shortcuts to manage them inside VSCode, but that's probably a lot of work and draw.io interface on this subject seams inadequate.

**Comment by hediet** [comment]
> You can't redirect the top iframe, it violate some security settings.
At least it doesn't work in the inspector.

I saw an extension doing this, so I wouldn't rule it out yet.
