### ISSUE TITLE
Unable to install because it is not compatible with the current version of VS Code (version 1.43.2).

### ISSUE THREAD

**Issue by dolfly** [hediet/vscode-drawio#46]
Unable to install 'eighthundreds.vscode-drawio' extension because it is not compatible with the current version of VS Code (version 1.43.2).

**Comment by hediet** [comment]
> eighthundreds.vscode-drawio

This is not my extension. [This is.](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)
