### ISSUE TITLE
Drawings and confidentiality

### ISSUE THREAD

**Issue by danardf** [hediet/vscode-drawio#49]
What about drawings and confidentiality?
Is the drawing is transmited to Draw.io server or there's no data sent to Draw.io, ... stays on local?

**Comment by hediet** [comment]
If you use the offline mode (which is enabled by default), no data is sent to anything. Everything stays local.

Even if you use the online mode (which you need to enable explicitly in the settings), no data leaves your computer (at least in theory - a draw.io online update could do whatever they want).
