### ISSUE TITLE
View reset on save

### ISSUE THREAD

**Issue by JoshuaWalsh** [hediet/vscode-drawio#5]
If I make changes to a diagram and then save it, the zoom level and view position are reset to their default.

**Comment by hediet** [comment]
[Kind of fixed](https://github.com/hediet/vscode-drawio/blob/master/src/DrawioTextEditorProvider.ts#L42) in v0.3.0.

However, it might still happen from time to time. You can always use the undo operation from VS Code though if the undo stack gets destroyed.

**Comment by hediet** [comment]
It does not happen as often as I thought. If it is still problematic, please open a new issue!
