### ISSUE TITLE
Draw.io is now called diagrams.net

### ISSUE THREAD

**Issue by impressivewebs** [hediet/vscode-drawio#52]
Not sure if you want to eventually change the name of this VS Code extension, but the draw.io app now redirects to diagrams.net, and it's been renamed.

**Comment by hediet** [comment]
I don't to plan to unless Draw.io wants me to rename it. I asked them, they are fine with it. Also, imho `Draw.io` is the much stronger brand.

**Comment by davidjgraph** [comment]
draw.io is fine. It's more that we don't trust the .io TLD security-wise, so recommend calls go to diagrams.net. Literally, nobody calls it diagrams.net.

**Comment by jpihl** [comment]
Hi @hediet, thanks for a great plugin!

I think it would be nice if the readme contained the world `diagrams.net`.
For new users of diagrams.net (like myself) who isn't aware of the name change, it can be difficult to find this nice plugin.
 
VS Code's Extensions Marketplace uses the plugin name and readme to provide search results, so currently this pluigin doesn't appear when searching for "diagrams.net".
