### ISSUE TITLE
Unable to change the color theme due to write error.

### ISSUE THREAD

**Issue by ekitagawa** [hediet/vscode-drawio#58]
### Description:

Unable to change the color theme with the following error:
```
Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.
```
<img width="458" alt="error_popup" src="https://user-images.githubusercontent.com/25517666/82716195-1494d580-9c4b-11ea-9db2-7bef9fc2804c.png">

### Steps to Reproduce:

1. Go to `Preference/Settings`
2. Scroll down to `extensions/Draw.io integration`
3. Change `Theme` to any one of theme
4. The error above is shown, and color does not change.

### Environment:

  OS: Mac Catalina (10.15.4)
  VS Code: Version: 1.45.1
 
### Workaround:
1. Right click the gear icon on upper left.
<img width="770" alt="gear_icon" src="https://user-images.githubusercontent.com/25517666/82716142-dd262900-9c4a-11ea-872e-398d43bdd505.png">

2. Select Setting as JSON `Copy Setting as JSON`
    You should get something like this: 
``` json
"hediet.vscode-drawio.theme": "automatic"
```

3. Click `Edit in setting.json`
<img width="670" alt="edit" src="https://user-images.githubusercontent.com/25517666/82716124-d13a6700-9c4a-11ea-9906-142dc4317479.png">

4. Insert the line from step 2 (with extra `,` at the end in case you will add more stuff later)
``` json
    "hediet.vscode-drawio.theme": "min",
```
5. Save the file, and make sure theme has been updated

**Comment by ekitagawa** [comment]
I really love this plugin!  This is a minor hiccup, and it could be env-specific.  Still, I figure it's worthwhile to record the workaround.

**Comment by hediet** [comment]
Thanks for detailed report and workaround!
However, I guess you really should check whether there are no JSON syntax errors in your setting.json file!

**Comment by ekitagawa** [comment]
ok.  good point... I made lots of lots of manual edits on mine.  I will flush it, and test again.

**Comment by ekitagawa** [comment]
yup... it was corrupt json after all.  Mine is long, so ran it through validator and fixed them.  The error is gone.  Closing this.  Thank you again for the pointer!

**Comment by ekitagawa** [comment]
yup... it was corrupt json after all. Mine is long, so ran it through validator and fixed them. The error is gone. Closing this. Thank you again for the pointer!
