### ISSUE TITLE
Ask Insider Users Whether The Build is Usable

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#59]
This feedback should be collected online, so that I now whether an insider build has been tested thoroughly enough to be released to production.

**Comment by MagicLegend** [comment]
Would it be possible to open up the packaged versions from your CI so I wouldn't have to pull and package the extension myself? Also maybe you should add an 'insiders' label for issues so people can open new issues that relate to the insiders version of the extension?

Also some instructions as to how to get and install (and use) the insiders version (basically the tl;dr of what you told me in #51 ) would be really useful.

**Comment by hediet** [comment]
This insiders build is uploaded to the marketplace! 😀 There are two drawio extensions now ;)

**Comment by MagicLegend** [comment]
I see, however; you still don't have the proposed api enabled it seems. Shouldn't you enable that on master? (given that they are insiders builds after all?)

**Comment by hediet** [comment]
Yeah. There is just no option to upload an extension to the marketplace that uses the proposed api at all. This insiders build allows me to test experimental features at least (not related to vscode insiders).
Even if I publish the vsix with enabled proposed api set to true, you still would need to start vscode with the --enablePropsedApi hediet.vscode-drawio flag... This is just a ux nightmare.
