### ISSUE TITLE
It seems we cannot export the draft as other formats, e.g., png, jpeg, pdf

### ISSUE THREAD

**Issue by longer-luo** [hediet/vscode-drawio#60]
Thanks for the great contribution. When I try to export the draft as other formats and click the download or device or open in new window, it backs to the draft and nothing happens.

**Comment by hediet** [comment]
Can you post a screenshot? The (buggy)
export menu item should not be visible anymore.
Or do you use the online mode?

**Comment by Duffyxx** [comment]
I get same problem, 
![image](https://user-images.githubusercontent.com/23207094/82865132-9f7e1480-9f58-11ea-99ec-cca2084c1f49.png)

then I export to png
![image](https://user-images.githubusercontent.com/23207094/82865213-cdfbef80-9f58-11ea-9209-5c6973d73a77.png)

get this
![image](https://user-images.githubusercontent.com/23207094/82865245-de13cf00-9f58-11ea-9b13-e6cc095d0ed8.png)

when I click Device or Download, nothing happens.
![image](https://user-images.githubusercontent.com/23207094/82865298-fa177080-9f58-11ea-8ebc-b6360d2162a7.png)

my system is OSX 10.15.4, vscode version is 1.45.1, and vscode-drawio version is v1.0.3 from vscode store.

Thanks.

**Comment by hediet** [comment]
I never published a version 1.0.3. Also, I removed this export option since it is broken and implemented a native export command.
Please check out my Drawio Insiders Build for the latest version.

**Comment by longer-luo** [comment]
thanks for the timely response!

**Comment by hediet** [comment]
@Duffyxx it seems that you have an old/invalid version too.

**Comment by Duffyxx** [comment]
Thanks, I find I install the wrong version.
