### ISSUE TITLE
Extension is inoperable in multi-root workspaces

### ISSUE THREAD

**Issue by petervandivier** [hediet/vscode-drawio#61]
It appears the extension stops functioning with the following error messages when used in a multi-root workspace.

> Unable to open 'bar.drawio': Assertion Failed: argument is undefined or null.

> An error occurred while loading view: hediet.vscode-drawio-text

Repro demonstrated [here](https://i.imgur.com/53j7C1u.mp4)

![Imgur](https://imgur.com/F54RKfX.gif)

## VS Code Environment

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

## Extensions

```
bbenoist.vagrant@0.5.0
blzjns.vscode-raml@3.0.1
bungcip.better-toml@0.3.2
DavidAnson.vscode-markdownlint@0.35.2
hediet.vscode-drawio@0.5.2
lextudio.restructuredtext@128.0.0
maelvalais.autoconf@0.1.0
mechatroner.rainbow-csv@1.7.0
ms-azure-devops.azure-pipelines@1.170.0
ms-azuretools.vscode-docker@1.2.0
ms-dotnettools.csharp@1.21.18
ms-python.python@2020.5.80290
ms-vscode.azure-account@0.8.11
ms-vscode.cpptools@0.28.1
ms-vscode.Go@0.14.3
ms-vscode.powershell@2020.4.0
rebornix.ruby@0.27.0
shd101wyy.markdown-preview-enhanced@0.5.9
smhrjn.ansys-apdl-syntax@0.0.11
timonwong.shellcheck@0.9.0
tommasov.hosts@1.1.1
twxs.cmake@0.0.17
vitaliymaz.vscode-svg-previewer@0.5.2
wingrunr21.vscode-ruby@0.27.0
```

**Comment by hediet** [comment]
Can you reproduce this with the [Insiders Build](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio-insiders-build)?

I changed the implementation for workspace configurations.

**Comment by hediet** [comment]
Nevermind, I can reproduce it.

**Comment by hediet** [comment]
This is a bug in VS Code. My code is not even called.

**Comment by petervandivier** [comment]
Not sure what's changed, but this [no longer appears to be an issue][1]

![ezgif-4-8288c96bec20](https://user-images.githubusercontent.com/10898767/88386527-7804c600-cda8-11ea-827e-ec70874448dc.gif)

Note: https://github.com/microsoft/vscode/issues/98603 remains open

[1]: https://i.imgur.com/FLDiUGl.mp4
