### ISSUE TITLE
I can't save the project in png format. When I click on save nothing happens

### ISSUE THREAD

**Issue by nelsonwenner** [hediet/vscode-drawio#62]
operational system: Ubuntu 18.04.4 LTS
vscode version: 1.45.1
vscode-drawio version: 0.5.2

I can't save the project in png format. When I click on save nothing happens.

screenshot:
![Screenshot from 2020-05-26 18-26-12](https://user-images.githubusercontent.com/40550247/82952275-09a9b000-9f7f-11ea-99d7-82d825d6ca7d.png)

**Comment by hediet** [comment]
Check out the [Insiders Build](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio-insiders-build). It has an "Draw.io: Export to PNG command".

**Comment by Videl** [comment]
Works for me. On Windows

**Comment by hediet** [comment]
I released v0.6.1 now ;)

**Comment by Ziip-dev** [comment]
Same behaviour than first post for me on Ubuntu 18.04:
I just tried the insider version 0.6.602

**Comment by hediet** [comment]
Please elaborate. Can you post a video / screenshots?

**Comment by Ziip-dev** [comment]
Sure! Here is what I have tried so far:
- operational system: Ubuntu 18.04.4 LTS
- vscode version: 1.45.1
- vscode-drawio insider version: 0.6.602

Actually I am setting up a neat workflow for reproducible research within vs code: writing/coding in Rmd notebooks, and relying on draw.io to create diagrams. Your extension thus allows not to even exit vs code while working on diagrams for a manuscript, which is wonderful :)

Ideally, saving a diagram as *.drawio.svg or *.drawio.png and linking to it from a Rmd file so it is imported within the document would be perfect, but knitr / latex struggle to manage .drawio extension apparently (I guess it doesn't play nice with embedded drawio info in the svg file but this is another story). Plus, draw.io extension doesn't want to open *.drawio.png file.
I have read all other issues, switched to insider version after that, and tried all the entries in the menus, but **export** was nowhere and **save&exit** does nothing when clicked: ![image](https://user-images.githubusercontent.com/62331138/83963188-4f7e4680-a8a4-11ea-8a98-4a5016587bd5.png)

Finally I tried the *online mode* of the extension which made appear the **export as** option in the *file* menu:
![image](https://user-images.githubusercontent.com/62331138/83963315-66716880-a8a5-11ea-8941-802d221ca34f.png)
It allowed me to retrieve diagrams as simple png files which is ok for knitr / latex to export, but, while this is not strictly blocking, any change requires to go back to editing the *.drawio file in online mode and exporting again to png.


Please feel free to ask if you want me to try anything else :)

**Comment by hediet** [comment]
Nice to hear that you like it! If you want to support further development/maintenance of this extension, [please consider sponsoring me](https://github.com/sponsors/hediet) ;)

There should be an export command that does what you want! (ctrl+shift+p, "Drawio: Export").
Also, you can configure this extension to edit *.svg files (see readme).

These draw.io export menus don't really work, this is why I disabled them. I cannot disable them in the online mode though.

**Comment by Ziip-dev** [comment]
Thank you for your answer and the great work :)

> There should be an export command that does what you want! (ctrl+shift+p, "Drawio: Export").

Yep, but the focus has to be outside of the draw.io window as this will be intercepted as show/hide right panel otherwise.

> Also, you can configure this extension to edit *.svg files (see readme).

Not sure this will be okay with Rmd notebooks but I will definitely give it a try :)

> These draw.io export menus don't really work, this is why I disabled them. I cannot disable them in the online mode though.

Actually they work pretty well in online mode, this how I manage to get my workflow working while waiting for the more seamless feature of png support

**Comment by hediet** [comment]
> Yep, but the focus has to be outside of the draw.io window as this will be intercepted as show/hide right panel otherwise.

This should not happen in offline mode.
In online mode I cannot prevent this, since draw.io is hosted in an iframe.

**Comment by Ziip-dev** [comment]
Got it! That's closer to what I am trying to achieve, thanks :)
