### ISSUE TITLE
Is it possible to print the document directly?

### ISSUE THREAD

**Issue by snoopy83101** [hediet/vscode-drawio#75]
MAC OS
When I press CMD+P, click "Print"

The printer is unresponsive and can only export the image, paste it in the HTML document, then open the HTML document, and print it in the browser with CMD+P.

This is very inconvenient.

**Comment by hediet** [comment]
Printing is not supported. VS Code does not allow you to print source too.
You can either use the drawio.svg feature and print the SVG using your browser or use the drawio website to print your diagram.

**Comment by mastoj** [comment]
What is the "draio.svg" feature?

**Comment by hediet** [comment]
You can convert drawio to svg files with the convert command. Those files are both valid svg and drawio files.

**Comment by mastoj** [comment]
and how do I do the conversion? Is that a menu option or is it the "File -> Embed -> Svg" thing?

**Comment by hediet** [comment]
It's F1 -> Drawio Convert –> Svg.

**Comment by mastoj** [comment]
Thanks!
