### ISSUE TITLE
Drawio interface doesn't show

### ISSUE THREAD

**Issue by izuchukwu67** [hediet/vscode-drawio#76]
After installing drawio extension, it still didn't work even after saving the file with a .drawio extension. Also, .drawio isn't in list of extensions

**Comment by hediet** [comment]
Can you show a screenshot of which extension you installed?
I need more details ;)

**Comment by hediet** [comment]
Please reopen if the problem still occurs. Also, please add details (like screenshots / screenrecordings) - otherwise I cannot help you!
