### ISSUE TITLE
Keyboard shortcuts taken over

### ISSUE THREAD

**Issue by stickeegreg** [hediet/vscode-drawio#77]
Pressing ctrl-p brings up a print menu instead of the VSCode file-switcher. Going to Help -> Keyboard Shortcuts within the plugin doesn't seem to do anything.

**Comment by hediet** [comment]
This is by design. To keep this extension simple, draw.io handles all shortcuts. Only those, not handled by draw.io are forwarded to VS Code.

**Comment by stickeegreg** [comment]
Makes sense. I guess real question is why doesn't the keyboard shortcuts window work - if it did I could just unbind the print shortcut myself. I could potentially help with this if you could give me a pointer as to where to start looking.

**Comment by hediet** [comment]
https://github.com/hediet/vscode-drawio/blob/master/src/DrawioAppServer/vscode.html#L259

> I guess real question is why doesn't the keyboard shortcuts window work

Yeah I need to remove that option.
Also, drawio shortcuts are not configurable afaik.

**Comment by hediet** [comment]
I think it makes sense do make drawio not listening to ctrl+p since printing does not make sense in VS Code (you should use the desktop app for that).

**Comment by hediet** [comment]
If you do a PR, please update the changelog. You can mention your github username in the changelog entry.
