### ISSUE TITLE
Support for Remote Development

### ISSUE THREAD

**Issue by juanperezro** [hediet/vscode-drawio#8]
Installed the extension on Visual Studio Code Insiders (1.46), using Remote-SSH.

When opening a .dio or .drawio file the editor is not displayed.

**Comment by hediet** [comment]
Can you try out disabling the offline mode?

**Comment by juanperezro** [comment]
When disabling the drawio offline mode it works as expected.

**Comment by nfour** [comment]
> When disabling the drawio offline mode it works as expected.

Can confirm

**Comment by hediet** [comment]
This is pretty much the same bug as [this](https://github.com/hediet/vscode-debug-visualizer/issues/50).

**Comment by hediet** [comment]
Fixed in v0.4.0.
