### ISSUE TITLE
padding for generated svg

### ISSUE THREAD

**Issue by timepp** [hediet/vscode-drawio#90]
when I use browser to view the SVG file generated there is no padding. so the objects border in SVG overlapped with browser border. anyway to improve?

**Comment by hediet** [comment]
You can add a node with transparent color to your diagram. That way you can realize your padding.

**Comment by timepp** [comment]
> You can add a node with transparent color to your diagram. That way you can realize your padding.

Thanks. This is also my current solution.

**Comment by hediet** [comment]
If you don't like that the background can be selected if you do this, you could also just use four invisible lines.
