### ISSUE TITLE
Associates all svg files with drawio

### ISSUE THREAD

**Issue by flatline01** [hediet/vscode-drawio#93]
Should only try to load `.drawio.svg` and not all .svg files.

![image](https://user-images.githubusercontent.com/3101184/84910323-bd84f380-b084-11ea-8b3f-2baadd332281.png)

additional info: 

```Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by hediet** [comment]
[This is already the case.](https://github.com/hediet/vscode-drawio/blob/master/package.json#L55)

Are you sure you didn't overwrite the settings? (see readme for how to overwrite the association)

**Comment by flatline01** [comment]
That fixed it. Almost certainly user error. This can be closed. Side note: This is an awesome extension.
