### ISSUE TITLE
Add ability to link to another file

### ISSUE THREAD

**Issue by tommck** [hediet/vscode-drawio#94]
Rather than having to embed everything all in one file, it would be really great if we could use a `file:/subfolder/file.drawio` link for the url.

This would allow us to separate things out much better in the case of a monorepo or other large folder structure.

**Comment by hediet** [comment]
Can you give more context to your problem / suggested solution?

> Rather than having to embed everything all in one file

What do you mean with that?

**Comment by tommck** [comment]
Well, as far as I can tell, there are 2 types of supported links.. "Page links" (pages in the same file) and URLs (which doesn't seem to support file:/ urls)

In my project, we have a monorepo with a bunch of different npm packages.  They have inter-dependencies.

I'd like to have a higher level "packages.drawio" file that shows design/relationships at the package level, but when you follow the link, I want it to open a completely different drawio file inside a folder below this one.

```
/dev/root/packages.drawio (high level diagram w/ links to the other files in sub-folders)
/dev/root/package1/package1.drawio (lower level diagrams - might link to sibling package diagrams as well)
/dev/root/package2/package2.drawio
...
```

When you're trying to document something large, using one file can get very cumbersome

**Comment by hediet** [comment]
> Well, as far as I can tell, there are 2 types of supported links.. "Page links" (pages in the same file) and URLs (which doesn't seem to support file:/ urls)

> but when you follow the link

Where do you use such links? I don't remember implementing anything related to that.
Do you use these links in markdown files?

**Comment by tommck** [comment]
When using the UML Package, you right-click and edit a link

![image](https://user-images.githubusercontent.com/981957/85021570-0483ef00-b140-11ea-9e77-32e582cc69e0.png)

**Comment by hediet** [comment]
Ah I was not aware of this feature.

Any extra functionality this extension provides should not lead to a lock-in though - draw.io should always be usable as a fallback if this extension does not work anymore.

Besides that, I'm happily accepting PRs! I don't use the link feature, so right now I don't have any incentive to investigate this use case.

**Comment by tommck** [comment]
OK.. that makes sense.  We'll see if I can look into it sometime, but I really doubt I will, sorry to say

**Comment by hediet** [comment]
This feature is supported for some versions now. See #169 for the issue.
